---

- name: Locally Check if csars folder exists
  local_action: "stat path={{ inventory_dir }}/resources/csars"
  register: csar_folder

- name: Create temporary folder
  tempfile:
    state: directory
    suffix: csar_a4c
  register: temp_dir
  when: csar_folder.stat.exists and csar_folder.stat.isdir

- name: Copy CSAR archives
  copy:
    src: "{{ inventory_dir }}/resources/csars/"
    dest: "{{ temp_dir.path }}"
  when: csar_folder.stat.exists and csar_folder.stat.isdir

- name: Get CSAR archives
  find:
    paths: "{{ temp_dir.path }}"
    patterns: "*.zip"
  register: cars_files
  when: csar_folder.stat.exists and csar_folder.stat.isdir

- name: Upload CSAR archive to A4C
  shell: "curl -k -X POST -H 'cookie: {{ session_id }}' -F file=@{{ item.path }} '{{ alien_url }}/rest/latest/csars'"
  with_items: "{{ cars_files.files | sort(attribute='path') | list }}"
  when: csar_folder.stat.exists and csar_folder.stat.isdir

- name: Finally remove temporary folder
  file:
    path: "{{ temp_dir.path }}"
    state: absent
  when: csar_folder.stat.exists and csar_folder.stat.isdir
