
- name: Detecting spark user
  set_fact:
    spark_user: "{{ lookup('vars', '{{ spark_user_var }}') }}"

- name: Here is the Spark user
  debug:
    var: spark_user

- name: Adding the SPARK_HOME env variable in the bashrc files for {{ spark_user }}
  become: true
  lineinfile:
    path: "{{ '/' if spark_user == 'root' else '/home' }}/{{ spark_user }}/.bashrc"
    line: "export SPARK_HOME={{ spark_home }}"
    state: present

- name: Ensure user {{ spark_user }} can launch Spark
  become: true
  become_user: "{{ spark_user }}"
  shell: "source ~/.bashrc && $SPARK_HOME/bin/spark-shell --version"
  register: spark_version

- name: Here is Spark version
  debug:
    var: spark_version.stderr_lines
