
- name: Define consul agent address
  set_fact:
    consulAgentIp: "{{ inventory_hostname }}{{ appendable_private_domain_name }}"

- name: Use localhost for consul agent address
  set_fact:
    consulAgentIp: "127.0.0.1"
  when: (use_localhost_for_local_connections)

- name: Setup consul template configuration
  template:
    src: consul_template.conf.j2
    dest: /etc/consul_template/consul_template.conf
    mode: 0444
    force: yes
    owner: "{{ a4c_user }}"
  become: true
  when: (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Setup initial sync script
  template:
    src: a4c-sync.init.j2
    dest: /var/lib/consul_template/a4c-sync.sh
    mode: 0700
    force: yes
    owner: "{{ a4c_user }}"
  become: true
  when: (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Setup sync script template for consul template
  template:
    src: a4c-sync.ctpl.j2
    dest: /etc/consul_template/a4c-sync.ctpl
    mode: 0444
    force: yes
    owner: "{{ a4c_user }}"
  become: true
  when: (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Locally Check for CA file
  local_action: "stat path={{ inventory_dir }}/{{ certificates_path }}/{{ ssl_ca_cert_name }}"
  register: stat_cacert_path
  when: (consul_tls) and (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- fail:
    msg: "The consul http communication should be secured by no CA file found in {{ inventory_dir }}/{{ certificates_path }}/{{ ssl_ca_cert_name }} ! Please provide CA certificate file."
  when: (consul_tls) and (a4c_ha_enabled) and (not stat_cacert_path.stat.exists)

- name: Locally Check for Host key file
  local_action: "stat path={{ inventory_dir }}/{{ certificates_path }}/{{ inventory_hostname }}{{ ssl_host_key_suffix }}"
  register: stat_hostkey_path
  when: (consul_tls) and (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- fail:
    msg: "The consul http communication should be secured by no host key file found in {{ inventory_dir }}/{{ certificates_path }}/{{ inventory_hostname }}{{ ssl_host_key_suffix }} ! Please provide host key file."
  when: (consul_tls) and (a4c_ha_enabled) and (not stat_hostkey_path.stat.exists) and (should_use_rsync_for_a4c_ha)

- name: Locally Check for Host cert file
  local_action: "stat path={{ inventory_dir }}/{{ certificates_path }}/{{ inventory_hostname }}{{ ssl_host_cert_suffix }}"
  register: stat_hostcert_path
  when: (consul_tls) and (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- fail:
    msg: "The consul http communication should be secured by no host certificate file found in {{ inventory_dir }}/{{ certificates_path }}/{{ inventory_hostname }}{{ ssl_host_cert_suffix }} ! Please provide host certificate file."
  when: (consul_tls) and (a4c_ha_enabled) and (not stat_hostcert_path.stat.exists) and (should_use_rsync_for_a4c_ha)

- name: Creates consul-template ssl directory
  file:
    path: "/etc/consul_template/ssl"
    state: directory
  become: true
  become_user: "{{ a4c_user }}"
  when: (consul_tls) and (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Copy CA cert file
  copy:
    src: "{{ inventory_dir }}/{{ certificates_path }}/{{ ssl_ca_cert_name }}"
    dest: "/etc/consul_template/ssl/{{ ssl_ca_cert_name }}"
  become: true
  become_user: "{{ a4c_user }}"
  when: (consul_tls) and (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Copy host key file
  copy:
    src: "{{ inventory_dir }}/{{ certificates_path }}/{{ inventory_hostname }}{{ ssl_host_key_suffix }}"
    dest: "/etc/consul_template/ssl/{{ inventory_hostname }}{{ ssl_host_key_suffix }}"
  become: true
  become_user: "{{ a4c_user }}"
  when: (consul_tls) and (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Copy host cert file
  copy:
    src: "{{ inventory_dir }}/{{ certificates_path }}/{{ inventory_hostname }}{{ ssl_host_cert_suffix }}"
    dest: "/etc/consul_template/ssl/{{ inventory_hostname }}{{ ssl_host_cert_suffix }}"
  become: true
  become_user: "{{ a4c_user }}"
  when: (consul_tls) and (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)
