
- name: Ensure ha_enabled variable is defined
  set_fact:
    ha_enabled: "{{ groups[ha_group] | length > 1 }}"

- name: Is the HA enabled ?
  debug:
    msg: "{{ groups[ha_group] }}"

- name: Is the HA enabled ?
  debug:
    var: ha_enabled

- name: Install nfs-utils
  yum:
    pkg: nfs-utils
    state: present
    update_cache: true
  become: true

- name: Ensure working_directory variable is defined
  set_fact:
    working_directory: "{{ lookup('vars', '{{ ha_group }}_working_dir') }}"

- name: Here is the working directory
  debug:
    var: working_directory

- name: Get the parent dir of the working directory
  shell: "echo $(dirname \"{{ working_directory }}\")"
  register: dirname_command_output

- name:
  set_fact:
    mount_directory: "{{ dirname_command_output.stdout }}"

- name: Here is the mount directory
  debug:
    var: mount_directory

- name: Creates NFS mount directory
  become: true
  file:
    path: "{{ mount_directory }}"
    state: directory

- name: UnMount NFS share
  become: true
  ignore_errors: yes
  shell: "umount {{ mount_directory }}"

- name: Mount NFS share
  become: true
  shell: "mount {{ nfs_share }} {{ mount_directory }}"

- name: Ensure working directory exists
  become: true
  file:
    path: "{{ working_directory }}"
    state: directory

- name: Clean the working directory
  become: true
  shell: "rm -rf {{ working_directory }}/*"
