---
- name: Create temporary folder
  tempfile:
    state: directory
  register: temp_dir

- name: "Upload artifact {{ inventory_dir }}/{{ resources_file_artifact }} on remote in {{ temp_dir.path }}/resources.yaml"
  copy:
    src: "{{ inventory_dir }}/{{ resources_file_artifact }}"
    dest: "{{ temp_dir.path }}/resources.yaml"

- name: "Stat {{ temp_dir.path }}/resources.yaml"
  stat: path="{{ temp_dir.path }}/resources.yaml"
  register: resources_file

- name: Slurp resources files
  slurp:
    src: "{{ temp_dir.path }}/resources.yaml"
  register: resources_slurped
  when: resources_file.stat.exists

- set_fact:
    resources_yaml: "{{resources_slurped['content'] | b64decode | from_yaml}}"
# - debug:
#     var: resources_yaml

- set_fact:
    resources: "{{resources_yaml['metaproperties']}}"
- debug:
    var: resources

# - debug:
#     msg: "{{item}}"
#   with_items: "{{resources}}"

- name: Create metaproperties
  uri:
    url: "{{ alien_url }}/rest/latest/metaproperties"
    method: POST
    return_content: yes
    validate_certs: no
    headers:
      Cookie: "{{ session_id }}"
      Content-Type: "application/json"
    body: "{{ item | to_json }}"
    body_format: json
    status_code: 200
  register: result
  with_items: "{{resources}}"
  ignore_errors: yes

# - debug:
#     var: result
