
- name: Here is the my_name var content
  delegate_to: localhost
  run_once: True
  debug:
    var: my_name
  when: (my_name is defined)

- name: my_name var is NOT defined
  debug:
    msg: my_name var is NOT defined
  when: (my_name is not defined)
