
- name: Enable A4C Remote JMX
  lineinfile:
    path: "{{ a4c_install_dir }}/alien4cloud/a4c.env"
    insertafter: '.*export JAVA_OPTIONS.*'
    line: 'export JAVA_OPTIONS="$JAVA_OPTIONS -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=12345 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"'
  become: true

- name: Restart service a4c
  service:
    name: a4c
    state: restarted
  become: true
