
- name: Start service Yorc
  service:
    name: yorc
    state: started
    enabled: yes
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Ensure Yorc is running
  command: systemctl status yorc
  ignore_errors: false
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Start Yorc
  shell:
    chdir: ~/yorc
    cmd: nohup ./yorc server > yorc.log 2>&1 & echo $! > yorc.pid
  when: ansible_distribution != 'CentOS' and ansible_distribution != 'Red Hat Enterprise Linux'

- name: Ensure Yorc is running
  shell:
    cmd: ps -ef |grep yorc |grep -v grep
  when: ansible_distribution != 'CentOS' and ansible_distribution != 'Red Hat Enterprise Linux'
