---

- set_fact:
    url: "{{ alien_url }}/login"

- name: Finally use this url to reach a4c
  debug:
    var: alien_url

- name: "Login onto A4C using {{url}}"
  uri:
    url: "{{url}}"
    method: POST
    body_format: form-urlencoded
    body:
    - [ username, "{{ a4c_admin_usr }}" ]
    - [ password, "{{ a4c_admin_pwd }}" ]
    - [ submit, Login ]
    return_content: yes
    validate_certs: no
    status_code: 302
    timeout: 120
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: result
  until: result.status == 302
  retries: 30
  delay: 30
  ignore_errors: yes

- name: Not able to logon to A4C after 30 retries, here is the unexpected result !
  debug:
    var: result
  when: (result.status != 302)

- name: Fail when fully started A4C is not reachable at {{ alien_url }}
  fail:
    msg: "Not able to login on A4C at {{ alien_url }} after 30 retries !"
  when: (result.status != 302)

- name: "Login onto A4C using {{url}}"
  uri:
    url: "{{url}}"
    method: POST
    body_format: form-urlencoded
    body:
    - [ username, "{{ a4c_admin_usr }}" ]
    - [ password, "{{ a4c_admin_pwd }}" ]
    - [ submit, Login ]
    return_content: yes
    validate_certs: no
    status_code: 302
    timeout: 120
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: login

- name: Getting session_id from cookie
  set_fact:
    session_id: "{{ login.set_cookie.split(';')[0] }}"

- name: here is the session_id
  debug:
    var: session_id

- name: "Get application list using {{ alien_url }}/rest/latest/applications/search"
  uri:
    url: "{{ alien_url }}/rest/latest/applications/search"
    method: POST
    return_content: yes
    validate_certs: no
    headers:
      Cookie: "{{ session_id }}"
    body_format: json
    body:
      from: 0
      size: 1
    status_code: 200
    timeout: 120
  register: result
  until: result.status == 200
  retries: 30
  delay: 30
  ignore_errors: yes

- name: Not able to get application list using rest API call, here is the unexpected result
  debug:
    var: result
  when: (result.status != 200)

- name: Not able to get application list using rest API call
  fail:
    msg: "Not able to get application list using rest API call {{ alien_url }}/rest/latest/applications/search after 30 retries !"
  when: (result.status != 200)

- name: Check if init directory exists
  stat:
    path: "{{ a4c_install_dir }}/alien4cloud/init"
  register: a4c_init_stat_result

- name: Get the a4c backup directory
  set_fact :
    a4c_backup_dir: "{{ a4c_install_dir }}"
  when: a4c_backup_dir is not defined

- name: Ensure a4c backup directory exit
  become: true
  file:
    path: "{{ a4c_backup_dir }}"
    state: directory
    owner: "{{ a4c_user }}"
  when: a4c_init_stat_result.stat.exists

- name: Ensure a4c backup directory exit
  become: true
  file:
    path: "{{ a4c_backup_dir }}/backups/init"
    state: directory
    owner: "{{ a4c_user }}"
  when: a4c_init_stat_result.stat.exists

- name: Rename the init directory
  command: "mv {{ a4c_install_dir }}/alien4cloud/init {{ a4c_backup_dir }}/backups/init/init_{{ ansible_date_time.iso8601 | replace(':', '') }}"
  when: a4c_init_stat_result.stat.exists
  become: true
  become_user: "{{ a4c_user }}"
