---

- set_fact:
    url: "{{ alien_url }}/login"

- name: Finally use this url to reach a4c
  debug:
    var: alien_url

- name: "Login onto A4C using {{url}}"
  uri:
    url: "{{url}}"
    method: POST
    body_format: form-urlencoded
    body:
    - [ username, "{{ a4c_admin_usr }}" ]
    - [ password, "{{ a4c_admin_pwd }}" ]
    - [ submit, Login ]
    return_content: yes
    validate_certs: no
    status_code: 302
    timeout: 120
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: result
  until: result.status == 302
  retries: 30
  delay: 30
  ignore_errors: yes


- name: Fail when fully started A4C is not reachable at {{ alien_url }}
  fail:
    msg: "Not able to login on A4C at {{ alien_url }} after 30 retries !"
  when: (result.status != 302)

- name: "Login onto A4C using {{url}}"
  uri:
    url: "{{url}}"
    method: POST
    body_format: form-urlencoded
    body:
    - [ username, "{{ a4c_admin_usr }}" ]
    - [ password, "{{ a4c_admin_pwd }}" ]
    - [ submit, Login ]    
    return_content: yes
    validate_certs: no
    status_code: 302
    timeout: 120
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: login

- name: Getting session_id from cookie
  set_fact:
    session_id: "{{ login.set_cookie.split(';')[0] }}"

- name: here is the session_id
  debug:
    var: session_id

- name: "Get application list using {{ alien_url }}/rest/latest/applications/search"
  uri:
    url: "{{ alien_url }}/rest/latest/applications/search"
    method: POST
    return_content: yes
    validate_certs: no
    headers:
      Cookie: "{{ session_id }}"
    body_format: json
    body:
      from: 0
      size: 1
    status_code: 200
    timeout: 120
  register: result
  until: result.status == 200
  retries: 30
  delay: 30
  ignore_errors: yes

- name: Not able to get application list using rest API call
  fail:
    msg: "Not able to get application list using rest API call {{ alien_url }}/rest/latest/applications/search after 30 retries !"
  when: (result.status != 200)
