---

- name: Create Location
  uri:
    url: "{{ alien_url }}/rest/latest/orchestrators/{{ orchestratorId }}/locations"
    method: POST
    return_content: yes
    validate_certs: no
    headers:
      Cookie: "{{ session_id }}"
    body:
      name: "{{ location_name }}"
      infrastructureType: "{{ location_type }}"
    body_format: json
    status_code: 201
  register: result

- set_fact:
    content: "{{ result.content }}"

- name: Export locationId
  set_fact:
    locationId: "{{ content.data }}"

- name: Populate locationIds
  set_fact:
    locationIds: "{{locationIds|default([])}}  + ['{{locationId}}']"
