{

"offline":"True",
"UNZIP_BIN": "unzip-6.0-15.1.el7.x86_64.rpm",
"ALIEN_DIST_URL": "resources/bin/alien4cloud-artemis-dist-2.2.0-SM8-dist.tar.gz",
"JAVA_DIST_URL": "resources/bin/java/jdk.tar.gz",
"CONSUL_DIST_URL": "resources/bin/consul_1.2.3_linux_amd64.zip",
"YORC_DIST_URL": "resources/bin/yorc-3.2.3.tgz",
"TERRAFORM_DIST_URL": "resources/bin/terraform_0.11.8_linux_amd64.zip",
"AWS_ACCESS_KEY": "",
"AWS_SECRET_KEY": "",
"AWS_REGION": "eu-west-1",
"a4c_protocol": "http",
"a4c_ip": "10.197.214.171",
"a4c_port": 8088,
"a4c_admin_usr": "admin",
"a4c_admin_pwd": "4dm1n",
"a4c_version": "2.2.0-SM8",
"discriminator": "ART_YORK_",
"ssl_keystore_source_location": "/var/folders/2d/3krvvvn538ggxjx8mtvwmj_c0000gn/T/tmp.vaCqIRYH/server-keystore.p12",
"ssl_src_keystore_password": "changeIt!",
"ssl_dest_keystore_password": "changeIt!",
"ssl_key_password": "changeIt!",
"dev_projects_path": "/Users/xdegenne/work/src",

"EOF": "" }
