---
- hosts: all
  name: Install all common dependencies.
  roles:
    - commons/check-distrib
    - commons/install-common-dependencies

- hosts: yorc
  name: Install configure and start Yorc.
  roles:
    - { role: commons/define_commons_vars, consul_agent_for: 'yorc' }
    - yorc/stop-yorc
    - consul/stop-consul
    - yorc/install-dependencies
    - consul/install-consul
    - { role: consul/configure-consul, consul_mode: 'client', consul_agent_for: 'yorc' }
    - install-java
    - yorc/install-yorc
    - yorc/configure-yorc
    - spark/install-spark
    - { role: spark/define-spark-home, spark_user_var: 'yorc_user' }
    - consul/start-consul
    - yorc/start-yorc

- hosts: yorcfront
  name: Install Yorc front (Nginx).
  roles:
    - commons/define_commons_vars
    - nginx/stop-nginx
    - nginx/install-nginx
    - yorc/configure-nginx
    - nginx/start-nginx
