---
- hosts: all
  name: Install all common dependencies.
  roles:
    - commons/check-distrib
    - commons/install-common-dependencies

- hosts: a4cfront
  name: Install A4C front (Nginx, consul and consul-template).
  roles:
    - { role: commons/define_commons_vars, consul_agent_for: 'a4cfront' }
    - nginx/stop-nginx
    - a4c_front/stop-consul-template
    - consul/stop-consul
    - nginx/install-nginx
    - consul/configure-consul-gossip-keygen
    - consul/install-consul
    - { role: consul/configure-consul, consul_mode: 'client', consul_agent_for: 'a4cfront' }
    - a4c_front/configure-nginx
    - a4c_front/install-consul-template
    - a4c_front/configure-consul-template
    - consul/start-consul
    - nginx/start-nginx
    - a4c_front/start-consul-template
