---
- hosts: all
  name: Install all common dependencies.
  become: false
  roles:
    - install-common-dependencies

- hosts: consul
  name: Install configure and start consul.
  become: false
  roles:
    - stop-consul
    - install-consul
    - configure-consul-gossip-keygen
    - { role: configure-consul, consul_mode: 'server' }
    - start-consul

- hosts: yorc
  name: Install configure and start Yorc.
  become: false
  roles:
    - stop-yorc
    - stop-consul
    - install-dependencies
    - install-consul
    - { role: configure-consul, consul_mode: 'client' }
    - install-yorc
    - configure-yorc
    - start-consul
    - start-yorc

- hosts: elasticsearch
  name: Install configure and start Elasticsearch.
  become: false
  roles:
    # - stop-elasticsearch
    - install-java
    - install-elasticsearch
    - configure-elasticsearch
    - start-elasticsearch

- hosts: a4c
  name: Install configure and start A4C.
  become: false
  roles:
    # - stop-a4c
    - install-java
    - install-a4c
    - configure-a4c
    - start-a4c
