---
- hosts: all
  name: Install a typical A4C stack with a Yorc orchestrator.
  become: false

  roles:
    - install-dependencies
    - install-consul
    - start-consul
    - install-yorc
    - configure-yorc
    - start-yorc
    - install-java
    - install-a4c
    - configure-a4c
    - start-a4c
