---
# ansible-playbook -K setup-a4c-sandbox.yml --extra-vars "@inputs.json" -v

- hosts: 127.0.0.1
  connection: local
  name: Setup A4C dev environment with a Yorc orchestrator for Artemis.
  become: false

  roles:
    # - { role: roles/upload_plugin,
    #     plugin_artifact: 'alien4cloud-repository-plugins/alien4cloud-http-repository-plugin/target/alien4cloud-http-repository-plugin-2.1.0-SNAPSHOT.zip',
    #     INSTANCE: 'local'
    #   }
    # - { role: roles/git,
    #     repositoryUrl: 'https://github.com/alien4cloud/tosca-normative-types.git',
    #     repositoryUsername: '',
    #     repositoryPassword: '',
    #     branchId: 'master',
    #     subPath: ''
    #   }
    # - { role: roles/git,
    #     repositoryUrl: 'https://github.com/alien4cloud/alien4cloud-extended-types.git',
    #     repositoryUsername: '',
    #     repositoryPassword: '',
    #     branchId: '2.1.0-SNAPSHOT',
    #     subPath: 'alien-base-types'
    #   }
    # - { role: roles/git,
    #     repositoryUrl: 'https://github.com/alien4cloud/docker-tosca-types.git',
    #     repositoryUsername: '',
    #     repositoryPassword: '',
    #     branchId: '2.1.0-SNAPSHOT',
    #     subPath: 'docker-types'
    #   }
    # - { role: roles/git,
    #     repositoryUrl: 'https://git.artemis.public/artemis_use_cases/service_applicatif.git',
    #     repositoryUsername: 'service_applicatif',
    #     repositoryPassword: 'service_applicatif',
    #     branchId: 'develop',
    #     subPath: ''
    #   }
    # - { role: roles/upload_plugin,
    #     plugin_artifact: 'alien4cloud-kubernetes-plugin/target/alien4cloud-kubernetes-plugin-2.1.0-SNAPSHOT.zip',
    #     INSTANCE: 'local'
    #   }
    # - { role: roles/upload_plugin,
    #     plugin_artifact: 'yorc-a4c-plugin/alien4cloud-yorc-plugin/target/alien4cloud-yorc-plugin-3.0.0-SNAPSHOT.zip',
    #     INSTANCE: 'local'
    #   }
    # - { role: roles/create_orchestrator,
    #     orchestratorName: 'Yorc',
    #     pluginId: 'alien4cloud-yorc-plugin',
    #     pluginBean: 'yorc-orchestrator-factory'
    #   }
    # - { role: 'roles/create_location',
    #     location_name: 'Default',
    #     location_type: 'OpenStack'
    #   }
    # - { role: 'roles/create_location_resources',
    #     resources_file_artifact: 'resources/location_resources.yaml'
    #   }
    # - { role: 'roles/add_location_modifiers',
    #     resources_file_artifact: 'resources/location_modifiers.yaml'
    #   }
    - { role: 'roles/remove_services',
        resources_file_artifact: 'resources/services.yaml'
      }
    - { role: 'roles/remove_services',
        resources_file_artifact: 'resources/a4c/config/locations/ROEM/services.yaml'
      }
    - { role: 'roles/remove_services',
        resources_file_artifact: 'resources/a4c/config/locations/AIS/services.yaml'
      }

    - { role: 'roles/a4c/config/get_orchectrator',
        orchestratorName: 'Yorc'
      }
    - { role: 'roles/create_location',
        location_name: 'ROEM',
        location_type: 'OpenStack'
      }
    - { role: 'roles/create_location_resources',
        resources_file_artifact: 'resources/a4c/config/locations/ROEM/location_resources.yaml'
      }
    - { role: 'roles/add_location_modifiers',
        resources_file_artifact: 'resources/location_modifiers.yaml'
      }
    - { role: 'roles/create_services',
        resources_file_artifact: 'resources/a4c/config/locations/ROEM/services.yaml'
      }
    - { role: 'roles/create_location',
        location_name: 'AIS',
        location_type: 'OpenStack'
      }
    - { role: 'roles/create_location_resources',
        resources_file_artifact: 'resources/a4c/config/locations/AIS/location_resources.yaml'
      }
    - { role: 'roles/add_location_modifiers',
        resources_file_artifact: 'resources/location_modifiers.yaml'
      }
    - { role: 'roles/create_services',
        resources_file_artifact: 'resources/a4c/config/locations/AIS/services.yaml'
      }
    - { role: 'roles/create_location',
        location_name: 'LID2',
        location_type: 'OpenStack'
      }
    - { role: 'roles/create_location_resources',
        resources_file_artifact: 'resources/a4c/config/locations/LID2/location_resources.yaml'
      }
    - { role: 'roles/add_location_modifiers',
        resources_file_artifact: 'resources/location_modifiers.yaml'
      }
    - { role: 'roles/create_services',
        resources_file_artifact: 'resources/a4c/config/locations/LID2/services.yaml'
      }
    - { role: 'roles/create_location',
        location_name: 'Similimages',
        location_type: 'OpenStack'
      }
    - { role: 'roles/create_location_resources',
        resources_file_artifact: 'resources/a4c/config/locations/Similimages/location_resources.yaml'
      }
    - { role: 'roles/add_location_modifiers',
        resources_file_artifact: 'resources/location_modifiers.yaml'
      }
    - { role: 'roles/create_services',
        resources_file_artifact: 'resources/a4c/config/locations/Similimages/services.yaml'
      }
