---
- hosts: a4cconfig
  name: Setup A4C with a Yorc orchestrator for Artemis.
  become: false

  roles:
    - commons/define_commons_vars
    - a4c/config/define_a4c_url
    # - { role: roles/git,
    #     repositoryUrl: 'https://github.com/alien4cloud/samples',
    #     repositoryUsername: '',
    #     repositoryPassword: '',
    #     branchId: 'develop',
    #     subPath: 'org/alien4cloud/mock'
    #   }
    - { role: 'a4c/config/get_orchectrator',
        orchestratorName: 'Yorc'
      }
    - { role: a4c/config/create_orchestrator,
        orchestratorName: 'Yorc',
        pluginId: 'alien4cloud-yorc-provider',
        pluginBean: 'yorc-orchestrator-factory'
      }
    - { role: 'a4c/config/create_metaproperties',
        resources_file_artifact: 'resources/metaproperties.yaml'
      }
    - { role: 'a4c/config/get_orchectrator',
        orchestratorName: 'Yorc'
      }
    # Create location
    - { role: 'a4c/config/create_location',
        location_name: 'Default',
        location_type: 'HostsPool'
      }
    - { role: 'a4c/config/create_location_resources',
        resources_file_artifact: 'resources/location_resources.yaml'
      }
    - { role: 'a4c/config/setup_location_modifier',
        pluginId: 'alien4cloud-kubernetes-plugin',
        beanName: 'kubernetes-adapter-modifier',
        phase: 'post-matched-node-setup',
        modifier_position: 1
      }
    - { role: 'a4c/config/setup_location_modifier',
        pluginId: 'alien4cloud-kubernetes-plugin',
        beanName: 'kubernetes-adapter-modifier',
        phase: 'post-matched-node-setup',
        modifier_position: 1
      }
    - { role: 'a4c/config/setup_location_modifier',
        pluginId: 'alien4cloud-k8s-spark-jobs',
        beanName: 'k8s-spark-jobs-modifier',
        phase: 'post-matched-node-setup',
        modifier_position: 2
      }
    - a4c/config/disable_plugins
    - a4c/config/upload_csars
    - { role: 'commons/parse_kubeconfig',
        resources_file_artifact: 'resources/kubeconfig'
      }
    - { role: 'a4c/config/create_services',
        resources_file_artifact: 'resources/services.yaml'
      }
