---
- hosts: a4cconfig
  name: Setup A4C with a Yorc orchestrator for Artemis.
  become: false

  roles:
    - { role: roles/a4c/config/define_a4c_url }
    # - { role: roles/git,
    #     repositoryUrl: 'https://github.com/alien4cloud/samples',
    #     repositoryUsername: '',
    #     repositoryPassword: '',
    #     branchId: 'develop',
    #     subPath: 'org/alien4cloud/mock'
    #   }
    - { role: 'roles/a4c/config/get_orchectrator',
        orchestratorName: 'Yorc'
      }
    - { role: roles/a4c/config/create_orchestrator,
        orchestratorName: 'Yorc',
        pluginId: 'alien4cloud-yorc-provider',
        pluginBean: 'yorc-orchestrator-factory'
      }
    - { role: 'roles/a4c/config/create_metaproperties',
        resources_file_artifact: 'resources/metaproperties.yaml'
      }
    # - { role: roles/git-ssl }
    # - { role: roles/git,
    #     repositoryUrl: 'https://34.242.16.28/artemis_use_cases/service_applicatif.git',
    #     repositoryUsername: 'service_applicatif',
    #     repositoryPassword: 'service_applicatif',
    #     branchId: 'develop',
    #     subPath: ''
    #   }
    # - { role: roles/git,
    #     repositoryUrl: 'https://git.artemis.public/artemis_use_cases/service_applicatif.git',
    #     repositoryUsername: 'service_applicatif',
    #     repositoryPassword: 'service_applicatif',
    #     branchId: 'develop',
    #     subPath: ''
    #   }
    - { role: 'roles/a4c/config/get_orchectrator',
        orchestratorName: 'Yorc'
      }
    # ROEM
    - { role: 'roles/a4c/config/create_location',
        location_name: 'Default',
        location_type: 'OpenStack'
      }
    - { role: 'a4c/config/setup_location_modifier',
        pluginId: 'alien4cloud-kubernetes-plugin',
        beanName: 'kubernetes-adapter-modifier',
        phase: 'post-matched-node-setup',
        modifier_position: 1
      }
    - { role: 'a4c/config/disable_plugin',
        pluginId: 'alien4cloud-datagouv_mls-plugin'
      }
    - { role: 'a4c/config/disable_plugin',
        pluginId: 'alien4cloud-ssi-network_policy-plugin'
      }
    - { role: 'a4c/config/disable_plugin',
        pluginId: 'alien4cloud-consul-publisher-plugin'
      }
    - { role: 'a4c/config/disable_plugin',
        pluginId: 'alien4cloud-supervision'
      }
    - a4c/config/upload_csars
