---

- name: Iterates on loadtests
  with_items: "{{ a4c_loadtests }}"
  include_role:
    name: loadtests/config/start_loadtest
  when: a4c_loadtests is defined
  vars:
    loadtest_instance: "{{ item }}"
