- name: Get the current user
  set_fact :
    a4c_user: "{{ ansible_user }}"
  when: a4c_user is not defined

- name: Get the a4c install directory
  set_fact :
    a4c_install_dir: "{{ ansible_env.HOME }}/a4c"
  when: a4c_install_dir is not defined

- name: Ensure a4c directory exists
  become: true
  file:
    path: "{{ a4c_install_dir }}"
    state: directory
    owner: "{{ a4c_user }}"

- name: Ensure a4c runtim directory exists
  become: true
  file:
    path: "{{ a4c_install_dir }}/runtime"
    state: directory
    owner: "{{ a4c_user }}"

- name: Check if a4c is already installed
  stat:
    path: "{{ a4c_install_dir }}/alien4cloud/alien4cloud.sh"
  register: a4c_stat_result

- name: Register a boolean indicating if A4C is already installed
  set_fact:
    a4c_installed: "{{ a4c_stat_result.stat.exists }}"

- debug:
    var: a4c_installed

- name: Extract alien4cloud archive from remote source
  unarchive:
    src: "{{ ALIEN_DIST_URL }}"
    dest: "{{ a4c_install_dir }}"
    mode: 0755
    remote_src: yes
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
        (offline is undefined) and
        (not a4c_installed)

- name: Extract alien4cloud archive from local source
  unarchive:
    src: "{{ ALIEN_DIST_URL }}"
    dest: "{{ a4c_install_dir }}"
    mode: 0755
    remote_src: no
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
        (offline is defined) and
        (not a4c_installed)

- name: Usage of a4c jinja2 template for service creation
  template:
    src: a4c-service.j2
    dest: /etc/systemd/system/a4c.service
    mode: 0444
    force: yes
  become: true
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and
        (not a4c_installed)

- name: Reload the deamon
  systemd:
    daemon_reload: yes
  become: true
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and
        (not a4c_installed)

- name: Enable a4c service
  command: systemctl enable a4c.service
  become: true
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and
        (not a4c_installed)
