
- name: Start nginx service
  service:
    name: nginx
    state: started
    enabled: yes
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
