
- name: Schedule workinig directory sync each minute
  become: true
  become_user: "{{ a4c_user }}"
  cron:
    name: "Sync working directory"
    minute: "*"
    hour: "*"
    job: "/var/lib/consul_template/a4c-sync.sh -f >> {{ a4c_log_dir }}/sync.log 2&>1"
