
- name: Ensure a4c_ha_enabled variable is defined
  set_fact:
    a4c_ha_enabled: "{{ groups['a4c'] | length > 1 }}"

- name: Is the HA enabled ?
  debug:
    var: a4c_ha_enabled

- name: Ensure the 'offline' variable is defined
  set_fact :
    offline: false
  when: offline is not defined

- name: Get the current user
  set_fact :
    consul_template_user: "{{ ansible_user }}"
  when: consul_template_user is not defined

- name: Ensure /etc/consul_template directory exists
  become: true
  file:
    path: "/etc/consul_template"
    state: directory
    owner: "{{ consul_template_user }}"
  when: (a4c_ha_enabled)

- name: Ensure /var/lib/consul_template/ directory exists
  become: true
  file:
    path: "/var/lib/consul_template/"
    state: directory
    owner: "{{ consul_template_user }}"
  when: (a4c_ha_enabled)

- name: Ensure /var/log/consul_template/ directory exists
  become: true
  file:
    path: "/var/log/consul_template/"
    state: directory
    owner: "{{ consul_template_user }}"
  when: (a4c_ha_enabled)

- name: Check if consul_template is installed
  shell: "/var/lib/consul_template/consul-template --version"
  register: is_consul_template_exist_command
  ignore_errors: yes
  become: true
  become_user: "{{ consul_template_user }}"

- name: Register a boolean indicating if consul_template is already installed
  set_fact:
    consul_template_installed: "{{ is_consul_template_exist_command.rc == 0 }}"

- name: Is consul_template installed ?
  debug:
    var: consul_template_installed

- name: Extract consul_template archive from remote source
  unarchive:
    src: "{{ CONSUL_TEMPLATE_DL_URL }}"
    dest: "/var/lib/consul_template"
    mode: 0755
    remote_src: yes
  become: true
  become_user: "{{ consul_template_user }}"
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
        (not offline) and
        (not consul_template_installed) and
        (a4c_ha_enabled)

- name: Extract consul_template archive from local source
  unarchive:
    src: "{{ CONSUL_TEMPLATE_DL_URL }}"
    dest: "/var/lib/consul_template"
    mode: 0755
    remote_src: no
  become: true
  become_user: "{{ consul_template_user }}"
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
        (offline) and
        (not consul_template_installed) and
        (a4c_ha_enabled)

- name: Usage of a4c-front-service jinja2 template for service creation
  template:
    src: a4c-front-service.j2
    dest: /etc/systemd/system/a4c-front.service
    mode: 0444
    force: yes
  become: true
  when: (a4c_ha_enabled) and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: Reload the deamon
  systemd:
    daemon_reload: yes
  become: true
  when: (a4c_ha_enabled) and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: Enable a4c-front service
  command: systemctl enable a4c-front.service
  become: true
  when: (a4c_ha_enabled) and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and
        (not consul_template_installed)
