---

- name: Install pip
  yum: pkg=python-pip state=present

- name: Ensure httplib2 is installed
  pip:
    name: httplib2
    state: present
  become: true

- name: Create CSAR GIT repository
  uri:
    url: "{{ alien_url }}/rest/latest/csarsgit"
    method: POST
    return_content: yes
    validate_certs: no
    HEADER_cookie: "{{ session_id }}"
    body:
      repositoryUrl: "{{ repositoryUrl }}"
      username: "{{ repositoryUsername }}"
      password: "{{ repositoryPassword }}"
      storedLocally: true
      importLocations:
        - branchId: "{{ branchId }}"
          subPath: "{{ subPath }}"
    body_format: json
  register: result

- name: "Register repository_id with value <{{ result.json.data }}> for attribute parsing"
  set_fact:
    repository_id: "{{ result.json.data }}"

- name: Import CSAR GIT repository
  uri:
    url: "{{ alien_url }}/rest/latest/csarsgit/{{ repository_id }}"
    method: POST
    return_content: yes
    validate_certs: no
    HEADER_cookie: "{{ session_id }}"
    timeout: 3000
  register: result
