#spark_download_url: http://archive.apache.org/dist/spark/spark-2.4.4/spark-2.4.4.tgz
spark_download_url: http://archive.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz
#spark_download_url: https://archive.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz
spark_expected_home: "/var/lib/spark/spark-2.4.4-bin-hadoop2.7"
spark_install_dir: /var/lib/spark
