
- name: Stop smb service
  service:
    name: smb
    state: stopped
    enabled: yes
  become: true
  ignore_errors: yes

- name: Stop nmb service
  service:
    name: nmb
    state: stopped
    enabled: yes
  become: true
  ignore_errors: yes
