- name: Install epel-release
  yum:
    pkg: epel-release
    state: present
    update_cache: true
  become: true
  ignore_errors: yes
  when: (not offline) and (not ((dont_install_epel is defined) and (dont_install_epel)))

- name: "FIXME : remove /etc/yum.repos.d/epel.repo"
  become: true
  file:
    path: /etc/yum.repos.d/epel.repo
    state: absent
  when: (not offline) and (not ((dont_install_epel is defined) and (dont_install_epel)))

- name: "FIXME : remove /etc/yum.repos.d/epel.repo"
  become: true
  file:
    path: /etc/yum.repos.d/epel7.repo
    state: absent
  when: (not offline) and (not ((dont_install_epel is defined) and (dont_install_epel)))
