
# - pause:
#     prompt: "Do you want to remove all consul files on {{ a4c_ip }}  (type 'yes I do !' to confirm) ?"
#   register: ask_for_confirmation
#   delegate_to: localhost

# - fail:
#     msg: "Aborted by user."
#   when: ask_for_confirmation.user_input != "yes I do !"

- name: Remove Elasticsearch package
  yum:
    name: "elasticsearch"
    state: removed
  become: true

- name: Remove Elasticsearch files
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/elasticsearch
    - /etc/elasticsearch
    - "{{ elasticsearch_home }}"
