services:

#   - nodeType: "org.alien4cloud.kubernetes.api.types.nodes.KubeCluster"
#     nodeTypeVersion: "3.1.0"
#     name: "KubeCluster"
#     version: "1.0-SNAPSHOT"
#     nodeInstance:
#       properties:
#         config: |
# {-{ kube_config | indent( width=10, indentfirst=True) }-}


  - nodeType: "org.alien4cloud.kubernetes.api.types.nodes.KubeCluster"
    nodeTypeVersion: "3.1.0"
    name: "KubeCluster"
    version: "0.1.0-SNAPSHOT"
    nodeInstance:
      properties:
        config: "apiVersion: v1\nclusters:\n- cluster:\n    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01ETXhNakl3TURVd09Gb1hEVE13TURNeE1ESXdNRFV3T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXlVClg0dkRtdlpuaS9wT1M4UWxyYVFFNWZhZGttOVR3bWdWczlBa2Y3NFM0MytBNEZ0YjNVZkhvVVl1TDhhYndmZTMKOGl3cTVESTB4YUcvbjVpSjZ6UU11Qnl2V25xbjY4VU9kNGtpaVZOa3o1N2FaVndVTHFWeGo3NEpqenhlQ1Q4QwpONTVHTWtaQXNwWFBQeldpem45M1lCWVcyT2lwcnI0YlFFRmlsWE8wd3VjZTNBOVNaMzVEeGdnT2lWbnFyMVZQCmpkbEZ5UFo0OWVudHJpTzYrSDFPUDY5SG50WWVQb0t6M3RnOWxjZDdQQlN2YW5XM0VXTEJUVXVTL0JnSnZGcmsKRVpBTytLSmVveUFKVE0wNytadXZrdW5xK01pN3hsalA4cFJOcmRwdFZNaU5jcVJBZDRWclZ6WWZYU0NhdzZUawpobWFjUGZjVzREeW1kbklueWNVQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDUmRMNGxsMXV5d2FFR2FXeXA3Q1Q4SEdYSjEKckJua0YwVGpyWGVldDA4RkpEOEZvV2FCNDlZVWQxMXFYcFVORlRLZ3UvdTl6TzgxaGlvRklKMUdqcUVMeDFKRQpyaXB6c1VSSWIzQ25FWTltd1ZYRmEveEo0M1RaMWxaQjAvKzQ0TVgzREhMYUZiUENLNU1hbjU4RWMrNU1kMW1zClFSQ1FXQTIvWEJGR2hoNUdJTks3SVF3OUJ6TGlOZk93UElRZkI1NUJ0MEFFeDVWZ3JhUHhmNHQvTW5EQlBXWjUKY1RvcmtsbW52STZMOWlUZldBK2RjNUpmYnA5RmlDeXZVRzJ4NVVzUGVEVVlyY3NpWDJwc0lEbU9Ca1VtRWhUUApuTU82Z2FpZCtSWHlHK2FNWFNGUlJaYmtOc3RzYTZhRnVJeVErTlZpV0h3L2JzOWdHMFNDYXVySlVBUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=\n\
            \    server: https://kubernetes.technique.artemis\n  name: cluster.local\ncontexts:\n\
            - context:\n    cluster: cluster.local\n    namespace: cufictif\n    user: kubernetes-admin\n\
            \  name: kubernetes-admin@cluster.local\ncurrent-context: kubernetes-admin@cluster.local\n\
            kind: Config\npreferences: {}\nusers:\n- name: kubernetes-admin\n  user:\n   \
            \ client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJZVRnQmwxTENvSDh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TURBek1USXlNREExTURoYUZ3MHlNVEF6TVRJeU1EQTFNRGxhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTM0KzJzazl6UGFnc0p4VXgKa3RYMWk1YUpqMXZ4N3NnTmw5aFZyS1V5RS90YjA5bWM4UzRueVV4R3BCVmJaSDJ0OEozWnY1MjJrNEhUMis1NApFV0xkQ0kxbEx3dHFtb1g2YUtISVlURDVRQURmZTdmaW5HM1o0cGtuRGgzNUN2cHhaMWJpdTdUdHBtRm51dW0yCkhPbzhhTEFpMTI4WmJYeWFzK1J2b1dvMFkySXJBU09sZmNKRWtDTGZNTXRjU0JZeGhLZXFjU24xNldIVDdvNW8KQkVtYS82eGtiUWZtTGRJalRQWEp1eXVCdkpPMzllM3lIdG1tWGtaVkNvRUYzYTdJVlEzZW1ndjNZZkNnVnhzMgo4dkloTnhhK0ptUEltS0VkTFB1cTduVWFYMlBRUUlyelRSNzBFRThaais0VHZqa0NmekZlb2VnWTExVjg0MmdBCjFVRFRId0lEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKbWpGVXB6QndFSlAzSGh5Q0YvM2J4eDVQRkFiNGNydW9hTwpBM2c3ZGRQdG1JanFPM2xUR0Vpbi9ocERkdVJ6a1d3WXV0RWZvYlJNR1hTV3ExSHBBOUZjRCtsL1NKTFNtWlhZCkg1aXVJaFl4czZuWTExZjJuSU5FZk1pK3N4UWp4YW01VThLRElITDRBV0loakNpaXlGemJhcXVuMXlCWUtLTGUKV2lrUVlIZ0hkemhhc2laaUt2bFdhVHh1eWcyVUg4ZDQxTTg0amhhQ1IyOEJNa3ZPbUhSeVIwMHNaTDdvcHJnMAp6bGc2VkoxWkFmczF6c2tLbVB2N0FNbFkrUFpiZk1IeHpFNWxDZmFYS2NOenI4OGRmMnM1b2ZQenN4dWpPSGVyCmtVYWUxelZXNEVQOGZ0eXFTdWdPQTZmK2hHSEd3Si9va0t4aGJqYXNZOHh2K0lUdzBURT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=\n\
            \    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBMzQrMnNrOXpQYWdzSnhVeGt0WDFpNWFKajF2eDdzZ05sOWhWcktVeUUvdGIwOW1jCjhTNG55VXhHcEJWYlpIMnQ4SjNadjUyMms0SFQyKzU0RVdMZENJMWxMd3RxbW9YNmFLSElZVEQ1UUFEZmU3ZmkKbkczWjRwa25EaDM1Q3ZweFoxYml1N1R0cG1GbnV1bTJIT284YUxBaTEyOFpiWHlhcytSdm9XbzBZMklyQVNPbApmY0pFa0NMZk1NdGNTQll4aEtlcWNTbjE2V0hUN281b0JFbWEvNnhrYlFmbUxkSWpUUFhKdXl1QnZKTzM5ZTN5Ckh0bW1Ya1pWQ29FRjNhN0lWUTNlbWd2M1lmQ2dWeHMyOHZJaE54YStKbVBJbUtFZExQdXE3blVhWDJQUVFJcnoKVFI3MEVFOFpqKzRUdmprQ2Z6RmVvZWdZMTFWODQyZ0ExVURUSHdJREFRQUJBb0lCQUVraE84UXNWU2d3SVBGUAo3MzEyMi9HamRyQWNoWkYwZzIzT2FJZ25LYkI3b3RnejhUQzd4bXdFdFg3ck5aQXp4SGhYU21seDc4MWt4S2JHCjVTUGEwUzhCQWI1WDM3Rllia2RYMUxKbVVNSnRCcTN6d3Y4a3VBZDF6ZDdDVXpzU0haS09TM0RYaUgzS2t5SUQKWFgwcjZrTGNpeWtwd0ltZUh3VUZqcmFnaFM2VXkzSzFlQzJ4WjRqeVM0eG1lbDRBUzdVc2tVWFlpbzRvd0FlZwpYcHhOdVdBOFFXcEJNWW50QmN1K1IxMHJqTXJ6dG5QbDlKR3pybytqKzBYTmhqTUE4Y0QrRk9MeDFjb21ieFBkCmIzQnN1eVpkVkpsdXVVS2lTZ2phZEdWSnAxSDhtVjZaQWhUOVU0bk9Gendpa1UveVh2bE5vMitxSzBtTWYrbUsKa3QyTkhNRUNnWUVBNGQxaXlGd1Ircys2ck54dTBTQnl2TWxGU09sQ2dUV2dWWUN4TUJYRmNSc1JQSVJQeUJTRQpuMHdhaWFneGdBNTlVWkdyNENaQitBQ0k4YzAybFYwblhFMWxTcmd1VG1VWXJUaWx2NHFoWEoySWszbkJDeThlCkVzcnk5akhNZkhaNW9OVXExRmN2aGszQ0Urd3RIbGkzWlB3VHdLMW5ZSEVZalRZdlVJc0E2TEVDZ1lFQS9XT24KSWFNMXpXTzRSUkc2Wk5kUUNXaXN2eXVsb1VoMVpxTXFjK1M0WmpLV2dMOUFXUUVnYloyeHJsTG1aakprYnFqawpkOE9GbVVNSVJmWXVuYTZiODhHN1I0UkNyUG50VzZCc1RjSHIvTTZSeVE1ZlQzYWE1RHA2YTgxSHovOFVPZ2h5CncrdGN1L0JXc3plamVFckpBNUUvUERZRW96NFg4cnV3U2ZsNmJNOENnWUFxV3h2bE91N2NQQXhqMGtxdHlRbjcKUVR0Tyt2OVB2OEM3aUJDeVZjTGEvUnAwWU5PZFQ4dTNHOHgyT0NaZ1AxZGM3cFp1eUgzaWhpY29RVFdWT1F6aQprRmtJZEJXcStlWnd4WWkvckwycDRwajBId2NHaytWdDNNVkhTZnR3ODc3SFhISlZzNnZqNGIwZGcxTEt1QlJjClNiRmlscUltUWM4NjNBaHZjRUhSWVFLQmdESmg2UzU0REUrZGYxdEViaUowNlhZbGVRdTkrdjM1c1ZaS0pUdk0KQTVwV2ZyUjAwcStmMkxuUy9DeGtVV21LcFl1WFMyNUEwMFNwSG5FQ3hUd1hKdTB0M1RZWUowWExvQlZ5N1hYOApsQmE5WUNGeEdTUnN1ZG1kZ3hBQ1RrQWVRUUJWQTdUUERLNVYySGRrSGIzaWFOdXJ1cjRYSTQ3dDNzY2w2S1NjCjFXbmpBb0dBVVV1Y0FLdUF2azVobGlVUWsyUjZOclRDN1lhUDZyK2ZUUDBnZFZlZ05hNTVaSWlMSEhrajBtaEUKWS8wcXBjTUdiN1dkazJ1cUs4Kzc1bkU4d0RNYnlUdUVqQ3pnSm01N3JKZDFQTDRVK0d2c3BxS3RUSHR5ckxXRgorRlp3YnBPcW1XY3BMVmdPeUlxWVRvR0JEaTFiUEtpaVpiSnUrNUIwT3dydzRLendFSjg9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="

        node_address: kubm-k8s00-worker-technique-1.technique.artemis

      capabilities:
        k8s_endpoint:
          properties:
            protocol: tcp

            secure: 'false'

            network_name: PRIVATE

            initiator: source

      attributeValues:
        state: initial

    # nodeInstance:
    #   capabilities:
    #     db:
    #       properties:
    #         port: "3306"
    #         database: "similimage_annot_faces"
    #         user: "elise_db_user"
    #         password: "elise_db_pwd"
    #   attributeValues:
    #     capabilities.db.ip_address: "mariadb.artemis.public"
    #     state: "started"

  # - nodeType: "artemis.mysql.pub.nodes.MysqlDbService"
  #   nodeTypeVersion: "a4c_version"
  #   name: "[SIM] Mysql search"
  #   version: "1.0-SNAPSHOT"
  #   nodeInstance:
  #     capabilities:
  #       db:
  #         properties:
  #           port: "3306"
  #           database: "similimage_search"
  #           user: "elise_db_user"
  #           password: "elise_db_pwd"
  #     attributeValues:
  #       capabilities.db.ip_address: "mariadb.artemis.public"
  #       state: "started"
  #
  # - nodeType: "artemis.elasticsearch.pub.nodes.ElasticSearchService"
  #   nodeTypeVersion: "a4c_version"
  #   name: "[SIM] Test_SE"
  #   version: "1.0-SNAPSHOT"
  #   nodeInstance:
  #     properties:
  #       index_basename: "uc_similimage_osint"
  #     capabilities:
  #       http:
  #         properties:
  #           port: "9200"
  #           protocol: "http"
  #     attributeValues:
  #       capabilities.http.ip_address: "http://elastic-1.artemis.public:9200/,http://elastic-2.artemis.public:9200/,http://elastic-3.artemis.public:9200/"
  #       state: "started"
  #
  # - nodeType: "artemis.hadoop.pub.nodes.HDFSService"
  #   nodeTypeVersion: "a4c_version"
  #   name: "[SIM] hadoop01"
  #   version: "1.0-SNAPSHOT"
  #   nodeInstance:
  #     capabilities:
  #       http_endpoint:
  #         properties:
  #           port: "50070"
  #           username: "root"
  #           path: "/similimage_1/osint_1/"
  #     attributeValues:
  #       capabilities.http_endpoint.ip_address: "hdfs-default.artemis.public"
  #       state: "started"
  #
  # - nodeType: "artemis.ceph.pub.nodes.CephBucket"
  #   nodeTypeVersion: "a4c_version"
  #   name: "[SIM] Ceph bucket"
  #   version: "1.0-SNAPSHOT"
  #   nodeInstance:
  #     capabilities:
  #       http:
  #         properties:
  #           port: "8000"
  #           bucket_name: "uc_simil_entrepot_image_osint"
  #           access_key: "SDXS70TGLZJGFUEB3A80"
  #           secret_key: "5yVZZxtJKNQox0dYoO5LGbIRgRbUnqsiez9bYWf8"
  #     attributeValues:
  #       capabilities.http.ip_address: "ceph.artemis.public"
  #       state: "started"
  # - nodeType: "artemis.ceph.pub.nodes.CephBucket"
  #   nodeTypeVersion: "a4c_version"
  #   name: "[SIM] Ceph bucket Imint"
  #   version: "1.0-SNAPSHOT"
  #   nodeInstance:
  #     capabilities:
  #       http:
  #         properties:
  #           port: "8000"
  #           bucket_name: "uc_simil_entrepot_image_imint"
  #           access_key: "SDXS70TGLZJGFUEB3A80"
  #           secret_key: "5yVZZxtJKNQox0dYoO5LGbIRgRbUnqsiez9bYWf8"
  #     attributeValues:
  #       capabilities.http.ip_address: "ceph.artemis.public"
  #       state: "started"
  # - nodeType: "artemis.ceph.pub.nodes.CephBucket"
  #   nodeTypeVersion: "a4c_version"
  #   name: "[SIM] Ceph bucket Sat"
  #   version: "1.0-SNAPSHOT"
  #   nodeInstance:
  #     capabilities:
  #       http:
  #         properties:
  #           port: "8000"
  #           bucket_name: "uc_simil_entrepot_image_sat"
  #           access_key: "SDXS70TGLZJGFUEB3A80"
  #           secret_key: "5yVZZxtJKNQox0dYoO5LGbIRgRbUnqsiez9bYWf8"
  #     attributeValues:
  #       capabilities.http.ip_address: "ceph.artemis.public"
  #       state: "started"
  # - nodeType: "artemis.mysql.pub.nodes.MysqlDbService"
  #   nodeTypeVersion: "a4c_version"
  #   name: "[SIM] Mysql search_imint"
  #   version: "1.0-SNAPSHOT"
  #   nodeInstance:
  #     capabilities:
  #       db:
  #         properties:
  #           port: "3306"
  #           database: "similimage_annot_satellite_1"
  #           user: "similimage_elise_1"
  #           password: "similimage_elise_1"
  #     attributeValues:
  #       capabilities.db.ip_address: "mariadb.artemis.public"
  #       state: "started"
