
- name: Stop service a4c
  service:
    name: a4c
    state: stopped
  become: true
  ignore_errors: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Get PID a4c
  command: ps -eo pid,command | grep alien | grep -v grep | awk '{print $1}'
  ignore_errors: yes
  register: a4c_pid
  when: ansible_distribution != 'CentOS' and ansible_distribution != 'Red Hat Enterprise Linux'

- name: Stop process a4c
  command: kill -9 {{ a4c_pid }}
  when: ansible_distribution != 'CentOS' and ansible_distribution != 'Red Hat Enterprise Linux'
