- name: Slurp inventory file
  delegate_to: localhost
  run_once: True
  slurp:
    src: "{{ data_dir }}/{{ inventory_resource_path }}"
  register: inventory_resource_slurped
  ignore_errors: yes

- name: Here is the inventory ressource
  debug:
    var: inventory_resource_slurped
  when: (inventory_resource_slurped is defined)

- name: Decode the inventory ressource content
  set_fact:
    inventory_resource_content: "{{ inventory_resource_slurped['content'] | b64decode }}"
  when: (inventory_resource_slurped is defined)
  ignore_errors: yes

- name: Here is the inventory ressource content
  debug:
    var: inventory_resource_content
  when: (inventory_resource_content is defined)
