
# - pause:
#     prompt: "Do you want to remove all yorc files on {{ a4c_ip }}  (type 'yes I do !' to confirm) ?"
#   register: ask_for_confirmation
#   delegate_to: localhost

- name: Remove yorc files
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ~/yorc
    - /etc/systemd/system/yorc.service
    - "{{ yorc_log_dir }}"
    - "{{ yorc_install_dir }}"
