
- name: Ensure the 'offline' variable is defined
  set_fact :
    offline: false
  when: offline is not defined

- name: List ansible packages and register result to print with debug later.
  yum:
    list: elasticsearch
  register: yum_list_result

- debug:
    var: yum_list_result

- name: Check elasticsearch rpm installed
  set_fact :
    elasticsearch_installed: "{{ yum_list_result.results|length > 0 and yum_list_result.results[0].yumstate == 'installed'}}"

- debug:
    var: elasticsearch_installed

# - name: Install Elasticsearch
#   yum:
#     pkg: "{{ item }}"
#     state: present
#     update_cache: true
#   become: true
#   with_items:
#     - unzip
#   when: (ansible_distribution == 'CentOS' or
#          ansible_distribution == 'Red Hat Enterprise Linux') and
#         (not elasticsearch_installed) and
#         (offline is undefined)

- name: Copy Elasticsearch
  copy:
    src: resources/bin/elasticsearch/
    dest: /tmp/rpms/
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
        (not elasticsearch_installed) and
        (offline)

- name: Get RPMs packages
  find:
    paths: /tmp/rpms/
    patterns: "*.rpm"
  register: rpm_files
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
        (not elasticsearch_installed) and
        (offline)

- name: Install RPMs
  yum:
    name: "{{ item.path }}"
    state: present
  become: true
  with_items: "{{ rpm_files.files | sort(attribute='path') | list }}"
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
        (not elasticsearch_installed) and
        (offline)

- name: Remove RMPs folder
  file:
    path: /tmp/rpms
    state: absent
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
        (not elasticsearch_installed) and
        (offline)

- name: Reload the systemd deamon
  systemd:
    daemon_reload: yes
  become: true
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and
        (not elasticsearch_installed)

- name: Enable elasticsearch service
  command: systemctl enable elasticsearch.service
  become: true
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and
        (not elasticsearch_installed)
