
- name: Create temporary folder
  tempfile:
    state: directory
  register: temp_dir

- name: Locally check {{ resources_file_artifact }} file
  local_action: "stat path={{ data_dir }}/{{ resources_file_artifact }}"
  register: stat_resources_file_artifact

- name: "Upload artifact {{ data_dir }}/{{ resources_file_artifact }} on remote in {{ temp_dir.path }}/resources.yaml"
  copy:
    src: "{{ data_dir }}/{{ resources_file_artifact }}"
    dest: "{{ temp_dir.path }}/resources.yaml"
  when: stat_resources_file_artifact.stat.exists

- name: "Stat {{ temp_dir.path }}/resources.yaml"
  stat: path="{{ temp_dir.path }}/resources.yaml"
  register: resources_file

- name: Slurp resources files
  slurp:
    src: "{{ temp_dir.path }}/resources.yaml"
  register: resources_slurped
  when: resources_file.stat.exists

- set_fact:
    kube_config: "{{ resources_slurped['content'] | b64decode }}"
  when: resources_file.stat.exists

- set_fact:
    kube_config: "Put your K8S config here"
  when: (not resources_file.stat.exists)

- debug:
    var: kube_config

- name: Finally remove temporary folder
  file:
    path: "{{ temp_dir.path }}"
    state: absent
