
- name: "Stat {{ resources_file_path }}"
  stat:
    path: "{{ resources_file_path }}"
  register: resources_file

- name: Slurp resources files
  slurp:
    src: "{{ resources_file_path }}"
  register: resources_slurped
  when: resources_file.stat.exists

- set_fact:
    resources_yaml: "{{resources_slurped['content'] | b64decode | from_yaml}}"
  when: (resources_file.stat.exists)

- name: Here is the resource content
  debug:
    var: resources_yaml
  when: (resources_yaml is defined)

- name: "{{ resources_file_path }} can not be found on remote"
  debug:
    msg: "{{ resources_file_path }} can't be found on remote"
  when: (resources_file.stat.exists)
