- name: show resource file
  debug:
    msg: "{{ lookup('template', file) }}"

- name: Create resource
  k8s:
    state: present
    namespace: "{{ namespace }}"
    kubeconfig: "{{ kubeConfig}}"           
    definition: "{{ lookup('template', file) }}"
    wait: yes
    wait_timeout: 240 
  vars:
    ansible_python_interpreter: /usr/bin/python3
