- name: Ensure inventory folder {{ inventory_dir }}/group_vars/all/ exists
  file:
    path: "{{ inventory_dir }}/group_vars/all/"
    state: directory

- name: Define content to write
  set_fact:
    var_content: "hello: World"

- name: Write a file in {{ inventory_dir }}/group_vars/all/hello.yml
  copy:
    content: "{{ var_content }}"
    dest: "{{ inventory_dir }}/group_vars/all/hello.yml"
