


- name: Ensure /etc/consul_template directory exists
  become: true
  file:
    path: "/etc/consul_template"
    state: directory
    owner: "{{ a4c_user }}"
  when: (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Ensure /var/lib/consul_template/ directory exists
  become: true
  file:
    path: "/var/lib/consul_template/"
    state: directory
    owner: "{{ a4c_user }}"
  when: (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Ensure /var/log/consul_template/ directory exists
  become: true
  file:
    path: "/var/log/consul_template/"
    state: directory
    owner: "{{ a4c_user }}"
  when: (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Check if consul_template is installed
  shell: "/var/lib/consul_template/consul-template --version"
  register: is_consul_template_exist_command
  ignore_errors: yes
  become: true
  when: (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Init a boolean indicating if consul_template is already installed
  set_fact:
    consul_template_installed: false

- name: Register a boolean indicating if consul_template is already installed
  set_fact:
    consul_template_installed: "{{ is_consul_template_exist_command.rc == 0 }}"
  when: (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Is consul_template installed ?
  debug:
    var: consul_template_installed
  when: (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Extract consul_template archive from remote source
  unarchive:
    src: "{{ CONSUL_TEMPLATE_DL_URL }}"
    dest: "/var/lib/consul_template"
    mode: 0755
    remote_src: yes
  become: true
  become_user: "{{ a4c_user }}"
  when: (not offline) and (not consul_template_installed) and (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Extract consul_template archive from local source
  unarchive:
    src: "{{ CONSUL_TEMPLATE_DL_URL }}"
    dest: "/var/lib/consul_template"
    mode: 0755
    remote_src: no
  become: true
  become_user: "{{ a4c_user }}"
  when: (offline) and (not consul_template_installed) and (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Usage of a4c-sync-service jinja2 template for service creation
  template:
    src: a4c-sync-service.j2
    dest: /etc/systemd/system/a4c-sync.service
    mode: 0444
    force: yes
  become: true
  when: (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Reload the deamon
  systemd:
    daemon_reload: yes
  become: true
  when: (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)

- name: Enable a4c-sync service
  command: systemctl enable a4c-sync.service
  become: true
  when: (not consul_template_installed) and (a4c_ha_enabled) and (should_use_rsync_for_a4c_ha)
