
- name: Define context vars based on component name
  include_role:
    name: rsync/define_context_vars
  vars:
    component_name: "{{ component_name }}"

- name: Ensure /etc/consul_template directory exists
  become: true
  file:
    path: "/etc/consul_template/{{ component_name }}"
    state: directory
    mode: 0777
    owner: "{{ component_user }}"
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Ensure /var/lib/consul_template/ directory exists
  become: true
  file:
    path: "/var/lib/consul_template/"
    state: directory
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: "Ensure /var/lib/consul_template/{{ component_name }} directory exists"
  become: true
  file:
    path: "/var/lib/consul_template/{{ component_name }}"
    state: directory
    owner: "{{ component_user }}"
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Ensure /var/log/consul_template/ directory exists
  become: true
  file:
    path: "/var/log/consul_template/"
    state: directory
    mode: 0777
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Check if consul_template is installed
  shell: "/var/lib/consul_template/consul-template --version"
  register: is_consul_template_exist_command
  ignore_errors: yes
  become: true
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Init a boolean indicating if consul_template is already installed
  set_fact:
    consul_template_installed: false

- name: Register a boolean indicating if consul_template is already installed
  set_fact:
    consul_template_installed: "{{ is_consul_template_exist_command.rc == 0 }}"
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Is consul_template installed ?
  debug:
    var: consul_template_installed
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Extract consul_template archive from remote source
  unarchive:
    src: "{{ CONSUL_TEMPLATE_DL_URL }}"
    dest: "/var/lib/consul_template"
    mode: 0777
    remote_src: yes
  become: true
  when: (not offline) and (not consul_template_installed) and (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Extract consul_template archive from local source
  unarchive:
    src: "{{ CONSUL_TEMPLATE_DL_URL }}"
    dest: "/var/lib/consul_template"
    mode: 0777
    remote_src: no
  become: true
  when: (offline) and (not consul_template_installed) and (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Usage of component-sync-service.j2 jinja2 template for service creation
  template:
    src: component-sync-service.j2
    dest: "/etc/systemd/system/{{ component_name }}-sync.service"
    mode: 0444
    force: yes
  become: true
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Reload the deamon
  systemd:
    daemon_reload: yes
  become: true
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: "Enable {{ component_name }}-sync service"
  command: "systemctl enable {{ component_name }}-sync.service"
  become: true
  when: (not consul_template_installed) and (component_ha_enabled) and (should_use_rsync_for_component_ha)
