
- name: Ensure the 'offline' variable is defined
  set_fact :
    offline: false
  when: offline is not defined

- fail:
    msg: "You can not specify an uid for yorc user that is root !"
  when: yorc_user is defined and yorc_user == "root" and yorc_uid is defined

- name: Add the user '{{ yorc_user }}' specifying uid
  user:
    name: "{{ yorc_user }}"
    uid: "{{ yorc_uid }}"
    # Ansible need a home for the yorc running user
    create_home: yes
    state: present
  become: true
  when: yorc_user is defined and yorc_user != "root" and yorc_uid is defined

- name: Add the user '{{ yorc_user }}'
  user:
    name: "{{ yorc_user }}"
    # Ansible need a home for the yorc running user
    create_home: yes
    state: present
  become: true
  when: yorc_user is defined and yorc_uid is not defined

- name: Get the current user
  set_fact :
    yorc_user: "{{ ansible_user }}"
  when: yorc_user is not defined

- name: Creates terraform plugins directory
  file:
    path: /var/terraform/plugins
    state: directory
  become: true

- name: Extract terraform from remote source
  unarchive:
    src: "{{ TERRAFORM_DIST_URL }}"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: yes
  become: true
  when: (not offline)

- name: Get terraform plugins from remote source
  unarchive:
    src: "{{ item }}"
    dest: /var/terraform/plugins
    mode: 0755
    remote_src: yes
  become: true
  with_items: "{{terraform_plugins}}"
  when: (not offline)

- name: Extract terraform from local source
  unarchive:
    src: "{{ TERRAFORM_DIST_URL }}"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: no
  become: true
  when: (offline)

- name: Copy terraform plugins
  copy:
    src: "{{ inventory_dir }}/resources/bin/terraform-plugins/"
    dest: /var/terraform/plugins.zip
  become: true
  when: (offline)

- name: Get terraform plugins files list
  find:
    paths: /var/terraform/plugins.zip
    excludes: readme.txt
  register: tp_files
  when: (offline)

- name : Init terraform plugins list
  set_fact:
     tp_list: []
  when: (offline)

- name : Build terraform plugins list
  set_fact:
     tp_list: "{{ tp_list + [ item.path ] }}"
  with_items: "{{tp_files.files}}"
  when: (offline)

- name : unzip terraform plugins
  unarchive:
    src: "{{ item }}"
    dest: /var/terraform/plugins
    remote_src: yes
  become: true
  with_items: "{{ tp_list }}"
  when: (offline)

- name: Creates yorc directory
  file:
    path: "{{ yorc_install_dir }}"
    state: directory
    owner: "{{ yorc_user }}"
  become: true

- name: Creates yorc logs directory
  file:
    path: "{{ yorc_log_dir }}"
    state: directory
    owner: "{{ yorc_user }}"
  become: true

- name: Check if yorc is already installed
  stat:
    path: "{{ yorc_install_dir }}/yorc"
  register: yorc_stat_result
  become: true
  become_user: "{{ yorc_user }}"

- name: Register a boolean indicating if yorc is already installed
  set_fact:
    yorc_installed: "{{ yorc_stat_result.stat.exists }}"

- name: This variable indicates if yorc is installed
  debug:
    var: yorc_installed

- name: Extract Yorc from remote source
  unarchive:
    src: "{{ YORC_DIST_URL }}"
    dest: "{{ yorc_install_dir }}"
    mode: 0755
    remote_src: yes
  become: true
  become_user: "{{ yorc_user }}"
  when: (not offline) and (not yorc_installed or (yorc_upgrade is defined and yorc_upgrade))

- name: Extract Yorc from local source
  unarchive:
    src: "{{ YORC_DIST_URL }}"
    dest: "{{ yorc_install_dir }}"
    mode: 0755
    remote_src: no
  become: true
  become_user: "{{ yorc_user }}"
  when: (offline) and (not yorc_installed or (yorc_upgrade is defined and yorc_upgrade))

- name: Define consul agent address
  set_fact:
    consulAgentIp: "{{ inventory_hostname }}{{ appendable_private_domain_name }}"

- name: Use localhost for consul agent address
  set_fact:
    consulAgentIp: "localhost"
  when: (use_localhost_for_local_connections)

- name: Define consul agent address
  set_fact:
    consul_agent_address: "{{ consulAgentIp }}:{{ consul_https_port }}"
  when: (_consul_tls)

- name: Define consul agent address
  set_fact:
    consul_agent_address: "{{ consulAgentIp }}:{{ consul_http_port }}"
  when: (not _consul_tls)

- name: Usage of yorc jinja2 template for service creation
  template:
    src: yorc-service.j2
    dest: /etc/systemd/system/yorc.service
    mode: 0444
    force: yes
  become: true

- name: Reload systemd
  systemd:
    name: yorc
    masked: yes
    daemon_reload: yes
  become: true

- name: Set service masked (will be unmasked at startup)
  systemd:
    name: yorc
    masked: yes
    enabled: no
  become: true
