- name: Instal the needed packages
  yum:
    pkg: ['samba', 'samba-client', 'samba-common']
    state: present
    update_cache: true
  become: true

- name: Creates samba directory
  file:
    path: "/var/samba"
    state: directory
    mode: 0777
  become: true
