- name: Instal the needed packages
  yum:
    pkg: "{{ item }}"
    state: present
    update_cache: true
  become: true
  with_items:
    - samba
    - samba-client
    - samba-common
  become: true

- name: Creates samba directory
  file:
    path: "/var/samba"
    state: directory
    mode: 0777
  become: true
