- name: Instal the needed package
  yum:
    pkg: "{{ item }}"
    state: present
    update_cache: true
  become: true
  with_items:
    - unzip
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - python
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  # TODO: do same for other distrib

- name: Instal the needed package
  yum:
    pkg: "{{ item }}"
    state: present
    update_cache: true
  become: true
  with_items:
    - python-pip
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install ansible
  command: pip install ansible==2.7.2
  become: true

- name: Extract terraform from remote source
  unarchive:
    src: "{{ TERRAFORM_DIST_URL }}"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: yes
  become: true

- name: Creates yorc directory
  file:
    path: ~/yorc
    state: directory

- name: Creates yorc directory
  file:
    path: ~/yorc/logs
    state: directory

- name: Extract Yorc from remote source
  unarchive:
    src: "{{ YORC_DIST_URL }}"
    dest: ~/yorc
    mode: 0755
    remote_src: yes

- name: Usage of yorc jinja2 template for service creation
  template:
    src: yorc-service.j2
    dest: /etc/systemd/system/yorc.service
    mode: 0444
    force: yes
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Reload the deamon before starting the service
  systemd:
    daemon_reload: yes
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
