
- name: Stop smb service
  service:
    name: smb
    state: stopped
    enabled: yes
  become: true
  ignore_errors: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Stop nmb service
  service:
    name: nmb
    state: stopped
    enabled: yes
  become: true
  ignore_errors: yes  
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
