
- name: Define context vars based on component name
  include_role:
    name: rsync/define_context_vars
  vars:
    component_name: "{{ component_name }}"
    
- name: "Stop {{ component_name }}-sync service"
  service:
    name: "{{ component_name }}-sync"
    state: stopped
    enabled: yes
  become: true
  ignore_errors: yes
