services:

  - nodeType: "artemis.mesos.dcos.pub.nodes.DcosService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] Dcos"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      capabilities:
        dcos_endpoint:
          properties:
            port: "80"
      attributeValues:
        capabilities.dcos_endpoint.ip_address: "dcos.artemis.public"
        state: "started"

  - nodeType: "artemis.kafka.pub.nodes.KafkaService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] Kafka"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      capabilities:
        kafka_endpoint:
          properties:
            port: "9092"
      attributeValues:
        capabilities.kafka_endpoint.ip_address: "10.197.214.166"
        state: "started"

  - nodeType: "artemis.zookeeper.pub.nodes.ZookeeperService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] Zookeeper"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      capabilities:
        zookeeper_endpoint:
          properties:
            port: "2181"
      attributeValues:
        capabilities.zookeeper_endpoint.ip_address: "kafka-1.external:9092,kafka-2.external:9092,kafka-3.external:9092"
        state: "started"

  - nodeType: "artemis.hadoop.pub.nodes.HDFSService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] HDFS (HTTP)"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      capabilities:
        http_endpoint:
          properties:
            port: "50070"
      attributeValues:
        capabilities.http_endpoint.ip_address: "hdfs-default.artemis.public"
        state: "started"

  - nodeType: "artemis.hadoop.pub.nodes.HDFSService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] HDFS (HDFS)"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      capabilities:
        hdfs_endpoint:
          properties:
            port: "8020"
      attributeValues:
        capabilities.hdfs_endpoint.ip_address: "hdfs-default.artemis.public"
        state: "started"

  - nodeType: "artemis.postgresql.pub.nodes.PostgreSQLService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] DeclarativeData"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      capabilities:
        postgresql_endpoint:
          properties:
            port: "5432"
            database: "ais_1"
            user: "ais_1"
            password: "ais_1"
      attributeValues:
        capabilities.postgresql_endpoint.ip_address: "postgres.external"
        state: "started"

  - nodeType: "artemis.kudu.pub.nodes.KuduService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] fresh_data"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      capabilities:
        kudu_endpoint:
          properties:
            port: "7051"
      attributeValues:
        capabilities.kudu_endpoint.ip_address: "kudumaster-1.external:7051,kudumaster-2.external:7051,kudumaster-3.external:7051"
        state: "started"

  - nodeType: "artemis.redis.pub.nodes.RedisService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] last_data"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      capabilities:
        redis_endpoint:
          properties:
            port: "7001"
      attributeValues:
        capabilities.redis_endpoint.ip_address: "redis.external"
        state: "started"

  - nodeType: "artemis.impala.pub.nodes.ImpalaService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] metastore"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      capabilities:
        impala_endpoint:
          properties:
            port: "21050"
      attributeValues:
        capabilities.impala_endpoint.ip_address: "impala.external"
        state: "started"

  - nodeType: "artemis.kafka.pub.nodes.TopicService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] ais-replay"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      properties:
        topic_name: "ais-replay"
      capabilities:
        kafka_topic:
          properties:
            port: "9092"
      attributeValues:
        capabilities.kafka_topic.ip_address: "kafka-1.external:9092,kafka-2.external:9092,kafka-3.external:9092"
        state: "started"

  - nodeType: "artemis.hadoop.pub.nodes.HdfsRepositoryService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] EDDJ Jar"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      capabilities:
        hdfs_repository:
          properties:
            port: "8022"
            path: "/spark_jar/ais/raw1toraw2/bigdata-core-spark-1.3.02-ARTEMIS-SNAPSHOT-jar-with-dependencies-artemis.jar"
      attributeValues:
        capabilities.hdfs_repository.ip_address: "hdfs-default.artemis.public"
        state: "started"

  - nodeType: "artemis.impala.pub.nodes.ImpalaRepositoryService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] Impala base"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      capabilities:
        impala_repository:
          properties:
            port: "21050"
            database_name: "ais_impala_1"
      attributeValues:
        capabilities.impala_repository.ip_address: "impala.external"
        state: "started"

  - nodeType: "artemis.impala.pub.nodes.ImpalaRepositoryService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] Impala shell"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      capabilities:
        impala_repository:
          properties:
            port: "21000"
            database_name: "ais_impala_1"
      attributeValues:
        capabilities.impala_repository.ip_address: "impala.external"
        state: "started"

  - nodeType: "artemis.hadoop.pub.nodes.HdfsRepositoryService"
    nodeTypeVersion: "a4c_version"
    name: "[AIS] HDFS Root repository"
    version: "1.0-SNAPSHOT"
    nodeInstance:
      capabilities:
        hdfs_repository:
          properties:
            port: "8020"
            path: "/ais_1/data/ais"
      attributeValues:
        capabilities.hdfs_repository.ip_address: "hdfs-default.external"
        state: "started"
