---

- name: Create temporary folder
  tempfile:
    state: directory
  register: temp_dir
  when: (csar_urls is defined)

- name: Download CSARs into {{ temp_dir.path }}
  get_url:
    url: "{{ item }}"
    dest: "{{ temp_dir.path }}/"
  with_items: "{{ csar_urls }}"
  when: (csar_urls is defined)

- name: Get CSAR archives
  find:
    paths: "{{ temp_dir.path }}/"
    patterns: "*.zip"
  register: cars_files

- name: Upload CSAR archive to A4C
  shell: "curl -k -X POST -H 'cookie: {{ session_id }}' -F file=@{{ item.path }} '{{ alien_url }}/rest/latest/csars'"
  with_items: "{{ cars_files.files | sort(attribute='path') | list }}"
