- name: Get the current user's home
  set_fact :
    a4c_install_dir: "{{ ansible_env.HOME }}/a4c"
  when: a4c_install_dir is not defined

- name: Create temporary folder
  tempfile:
    state: directory
  register: temp_dir

- name: Copy server keystore
  copy:
    src: "{{ ssl_keystore_source_location }}"
    dest: "{{ temp_dir.path }}/server-keystore.p12"
    mode: 0600
  when: a4c_protocol == 'https'

- name: Creates SSL directory
  file:
    path: "{{ a4c_install_dir }}/alien4cloud/ssl"
    state: directory
  when: a4c_protocol == 'https'

- name: Generate key store
  shell:
    cmd: "keytool -importkeystore -destkeystore {{ a4c_install_dir }}/alien4cloud/ssl/server-keystore.jks -srckeystore {{ temp_dir.path }}/server-keystore.p12 -srcstoretype pkcs12 -alias server -deststorepass {{ ssl_dest_keystore_password }} -srckeypass {{ ssl_key_password }} -srcstorepass {{ ssl_src_keystore_password }}"
  become: true
  when: a4c_protocol == 'https'

- name: Creates logs directory
  file:
    path: "{{ a4c_install_dir }}/alien4cloud/logs"
    state: directory

- name: Configure A4C
  template:
    src: alien4cloud-config.yml.j2
    dest: "{{ a4c_install_dir }}/alien4cloud/config/alien4cloud-config.yml"
    force: yes

- name: Remove temporary folder
  file:
    path: "{{ temp_dir.path }}"
    state: absent
