---

- name: Here is the key we need to look for in keypass
  debug:
    var: keypass_key

- name: Here is the key custom_property we need to look for in keypass
  debug:
    var: keypass_custom_property

- name: Here is the machine_name we need to get the certificates for
  debug:
    var: machine_name

- name: Here is the file_suffix_var_name
  debug:
    var: file_suffix_var_name

- name: Get the file file_suffix_var_name var
  set_fact:
    file_suffix: "{{ lookup('vars', file_suffix_var_name) }}"

- name: Define a var containing the local file path
  set_fact:
    local_certificate_file_path: "{{ inventory_dir }}/{{ certificates_path }}/{{ machine_name }}{{ file_suffix }}"

- name: Here is the local file name where we expect to find/write the certificate
  debug:
    var: local_certificate_file_path

- name: Locally Check for certificate file
  local_action: "stat path={{ local_certificate_file_path }}"
  register: local_certificate_file

- name: Does the local certificate file exist ?
  debug:
    var: local_certificate_file.stat.exists

- name: Get cert content
  set_fact:
    cert_content: "{{ lookup('keepass', keypass_key, 'custom_properties')[keypass_custom_property] }}"
  ignore_errors: yes
  when: not local_certificate_file.stat.exists

- name: Create temporary file to store certificate content
  tempfile:
    state: file
    suffix: temp
  register: cert_file
  when: not local_certificate_file.stat.exists and cert_content is defined and cert_content != ""

- copy:
    content: "{{ cert_content }}"
    dest: "{{ cert_file.path }}"
  when: not local_certificate_file.stat.exists and cert_content is defined and cert_content != ""

- name: Store certificate in a local file
  fetch:
    src: "{{ cert_file.path }}"
    dest: "{{ local_certificate_file_path }}"
    flat: yes
    validate_checksum: no
  when: not local_certificate_file.stat.exists and cert_content is defined and cert_content != ""

- name: Finally remove temporary folder
  file:
    path: "{{ cert_file.path }}"
    state: absent
  when: not local_certificate_file.stat.exists
