---

- name: Creates Loadtest directory
  file:
    path: "{{ jmeter_install_dir }}/loadtests"
    state: directory
    owner: "{{ jmeter_user }}"
  become: true

- name: Creates Results directory
  file:
    path: "{{ jmeter_install_dir }}/results"
    state: directory
    owner: "{{ jmeter_user }}"
  become: true

- name: Create Scenario
  template:
    src: application.jmx.j2
    dest: "{{ jmeter_install_dir }}/loadtests/application.jmx"
    force: yes
  become: true
  become_user: "{{ jmeter_user }}"

- name: Iterates on loadtests
  with_items: "{{ a4c_loadtests }}"
  include_role:
    name: loadtests/config/config_loadtest
  when: a4c_loadtests is defined
  vars:
    loadtest_instance: "{{ item }}"
