
- name: Start Yorc Once
  include_role:
    name: yorc/_start-yorc
  run_once: true
  when: yorc_ha_enabled and should_use_rsync_for_yorc_ha

- name: Start Yorc Once
  include_role:
    name: yorc/_start-yorc
  when: not (yorc_ha_enabled and should_use_rsync_for_yorc_ha)
