
- name: Locally Check for public key files
  local_action: "shell bash -c 'ls {{ inventory_dir }}/certificates/pub/*.pub'"
  register: pubkeys_ls

- debug:
    var: pubkeys_ls.stdout_lines

- name: Copy public keys
  become: true
  become_user: "{{ a4c_user }}"
  copy:
    src: "{{ item }}"
    dest: "~/.ssh/"
  with_items: "{{ pubkeys_ls.stdout_lines }}"

- name: Feeding authorized_keys with public keys
  become: true
  become_user: "{{ a4c_user }}"
  shell: "cat ~/.ssh/$(basename {{ item }}) >> ~/.ssh/authorized_keys"
  # args:
  #   chdir: "~/.ssh/"
  with_items: "{{ pubkeys_ls.stdout_lines }}"
