
- name: Locally Check for public key files
  local_action: "shell bash -c 'ls {{ inventory_dir }}/certificates/pub/*.pub'"
  register: pubkeys_ls

- name: Here are the public keys
  debug:
    var: pubkeys_ls.stdout_lines

- name: Copy public keys
  become: true
  become_user: "{{ a4c_user }}"
  copy:
    src: "{{ item }}"
    dest: "~/.ssh/"
    mode: 0400
    owner: "{{ a4c_user }}"
  with_items: "{{ pubkeys_ls.stdout_lines }}"

- name: Ensure authorized_keys exists
  become: true
  become_user: "{{ a4c_user }}"
  shell: "touch ~/.ssh/authorized_keys"

- name: Set authorized_keys permissions to 0600
  become: true
  become_user: "{{ a4c_user }}"
  file:
    path: "~/.ssh/authorized_keys"
    owner: "{{ a4c_user }}"
    mode: '0600'

- name: Feeding authorized_keys with public keys
  become: true
  become_user: "{{ a4c_user }}"
  shell: "cat ~/.ssh/$(basename {{ item }}) >> ~/.ssh/authorized_keys"
  with_items: "{{ pubkeys_ls.stdout_lines }}"

- name: Set authorized_keys permissions to 0400
  become: true
  become_user: "{{ a4c_user }}"
  file:
    path: "~/.ssh/authorized_keys"
    owner: "{{ a4c_user }}"
    mode: '0400'
