---

- name: initialize pvsize
  set_fact:
     pvsize: "{{ k8s.consul.pvsize | default(k8s_consul_pvsize) }}"

- name: display action
  debug:
     var: action

- name: perform action on consul pvs
  with_items: "{{ k8s.consul.pvfiles }}"
  include_role:
    name: k8s/consul/pv
  when: (k8s.consul.namespace is defined)
  vars:
    pvfile: "{{ item }}"

