
- name: Ensure the 'offline' variable is defined
  set_fact :
    offline: false
  when: offline is not defined

- name: Instal the needed package
  yum:
    pkg: ['epel-release', 'python']
    state: present
    update_cache: true
  become: true
  when: (not offline)

# - name: Instal the needed package
#   yum:
#     pkg: python-pip
#     state: present
#     update_cache: true
#   become: true
#   when: (not offline)

# - name: Install ansible
#   command: pip install ansible==2.7.2
#   become: true
#   when: (not offline)

- name: Install ansible and all python packages ({{item}})
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ yorc_dependencies_rpm_urls }}"
  when: (not offline) and (yorc_dependencies_rpm_urls is defined)

# FIXME: find a better way to perform this offline install

- name: Copy RPMs
  copy:
    src: resources/bin/rpms/
    dest: /tmp/rpms/
  when: (offline)

- name: Get RPMs packages
  find:
    paths: /tmp/rpms/
    patterns: "*.rpm"
  register: rpm_files
  when: (offline)

- name: Install RPMs
  yum:
    name: "{{ item.path }}"
    state: present
  become: true
  with_items: "{{ rpm_files.files | sort(attribute='path') | list }}"
  when: (offline)

- name: Remove RMPs folder
  file:
    path: /tmp/rpms
    state: absent
  when: (offline)

- name: Copy python and ansible
  copy:
    src: resources/bin/python/
    dest: /tmp/python/
  when: (offline)

- name: Get python and ansible files
  find:
    paths: /tmp/python
    excludes: readme.txt
  register: python_files
  when: (offline)

- name : Init python and ansible files list
  set_fact:
     python_list: []
  when: (offline)

- name : Build python and ansible files list
  set_fact:
     python_list: "{{ python_list + [ item.path ] }}"
  with_items: "{{python_files.files}}"
  when: (offline)

#- name: debug
#  debug:
#    var: python_list

- name: Install python and ansible
  yum:
    name: "{{python_list}}"
    state: present
  become: true
  when: (offline)

- name: Remove python folder
  file:
    path: /tmp/python
    state: absent
  when: (offline)

- name: Copy usr binaries
  copy:
    src: resources/bin/usr/
    dest: /tmp/usr/

- name: Get usr binaries
  find:
    paths: /tmp/usr/
    excludes: "readme.txt"
  register: usr_files

- name: Install usr binaries
  copy:
    src: "{{ item.path }}"
    remote_src: True
    dest: /usr/local/bin/
    mode: '0777'
  become: true
  with_items: "{{ usr_files.files | sort(attribute='path') | list }}"

- name: Remove usr folder
  file:
    path: /tmp/usr/
    state: absent
