
- name: Define context vars based on component name
  include_role:
    name: rsync/define_context_vars
  vars:
    component_name: "{{ component_name }}"

- name: Locally Check for public key files
  local_action: "shell bash -c 'ls {{ inventory_dir }}/certificates/pub/*.pub'"
  register: pubkeys_ls
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Here are the public keys
  debug:
    var: pubkeys_ls.stdout_lines
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Copy public keys
  become: true
  become_user: "{{ component_user }}"
  copy:
    src: "{{ item }}"
    dest: "~/.ssh/"
    mode: 0400
    owner: "{{ component_user }}"
  with_items: "{{ pubkeys_ls.stdout_lines }}"
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Ensure authorized_keys exists
  become: true
  become_user: "{{ component_user }}"
  shell: "touch ~/.ssh/authorized_keys"
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Set authorized_keys permissions to 0600
  become: true
  become_user: "{{ component_user }}"
  file:
    path: "~/.ssh/authorized_keys"
    owner: "{{ component_user }}"
    mode: '0600'
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Feeding authorized_keys with public keys
  become: true
  become_user: "{{ component_user }}"
  shell: "cat ~/.ssh/$(basename {{ item }}) >> ~/.ssh/authorized_keys"
  with_items: "{{ pubkeys_ls.stdout_lines }}"
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)

- name: Set authorized_keys permissions to 0400
  become: true
  become_user: "{{ component_user }}"
  file:
    path: "~/.ssh/authorized_keys"
    owner: "{{ component_user }}"
    mode: '0400'
  when: (component_ha_enabled) and (should_use_rsync_for_component_ha)
