- name: Ensure the 'offline' variable is defined
  set_fact :
    offline: false
  when: offline is not defined

- name: List elasticsearch packages and register result to print with debug later.
  yum:
    list: elasticsearch
  register: yum_list_result

- debug:
    var: yum_list_result

- name: Check elasticsearch rpm installed
  set_fact :
    elasticsearch_installed: "{{ yum_list_result.results|length > 0 and yum_list_result.results[0].yumstate == 'installed'}}"

- debug:
    var: elasticsearch_installed

- name: Install the Elasticsearch rpm from a remote repo
  become: true
  yum:
    name: "{{ elasticsearch_rmp_url }}"
    state: present
    disable_gpg_check: yes
  when: (not offline)

- name: Copy Elasticsearch
  copy:
    src: "{{ inventory_dir }}/resources/bin/elasticsearch/"
    dest: /tmp/rpms/
  when: (not elasticsearch_installed) and (offline)

- name: Get RPMs packages
  find:
    paths: /tmp/rpms/
    patterns: "*.rpm"
  register: rpm_files
  when: (not elasticsearch_installed) and (offline)

- name: Install RPMs
  yum:
    name: "{{ item.path }}"
    state: present
  become: true
  with_items: "{{ rpm_files.files | sort(attribute='path') | list }}"
  when: (not elasticsearch_installed) and (offline)

- name: Remove RMPs folder
  file:
    path: /tmp/rpms
    state: absent
  when: (not elasticsearch_installed) and (offline)

- name: Reload the systemd deamon
  systemd:
    daemon_reload: yes
  become: true
  when: (not elasticsearch_installed)

- name: Enable elasticsearch service
  command: systemctl enable elasticsearch.service
  become: true
  when: (not elasticsearch_installed)
