---

- name: Iterates on loadtests
  with_items: "{{ a4c_loadtests }}"
  include_role:
    name: playbooks/roles/loadtests/config/stop_loadtest
  when: a4c_loadtests is defined
  vars:
    loadtest_instance: "{{ item }}"
