---

- name: Login onto A4C
  uri:
    url: "{{ alien_url }}/login?username={{ a4c_admin_usr }}&password={{ a4c_admin_pwd }}&submit=Login"
    method: POST
    return_content: yes
    status_code: 302
    validate_certs: no
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: login

- set_fact:
    session_id: "{{ login.set_cookie.split(';')[0] }}"

# if a file is given as an artifact, upload it as a plugin for alien
- name: "Ensure the file {{ dev_projects_path }}/{{ plugin_artifact }} exists"
  local_action: "stat path={{ dev_projects_path }}/{{ plugin_artifact }}"
  register: stat_plugin_artifact
# - copy:
#     src: "{{ plugin_artifact }}"
#     dest: "/tmp/plugin_artifact_{{ INSTANCE }}.zip"
#   when: stat_plugin_artifact.stat.exists
- name: Upload plugin archive to A4C
  shell: "curl -k -X POST -H 'cookie: {{ session_id }}' -F file=@{{ dev_projects_path }}/{{ plugin_artifact }} '{{ alien_url }}/rest/latest/plugins'"
  when: stat_plugin_artifact.stat.exists
