
- name: Start smb service
  service:
    name: smb
    state: started
    enabled: yes
  become: true

- name: Start nmb service
  service:
    name: nmb
    state: started
    enabled: yes
  become: true
