
- name: Stop service elasticsearch
  service:
    name: elasticsearch
    state: stopped
  become: true
  ignore_errors: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
