- name: Fetch Java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: java_version
  changed_when: false

- debug:
    var: java_version

- name: Check java version
  set_fact :
   java8_installed: "{{ java_version.stdout|length > 0 and java_version.stdout is version_compare('1.8', '>=') }}"
    # java8_installed: false

- debug:
    var: java8_installed

- debug:
    msg: "Java 8 is installed"
  when: (java8_installed)

- debug:
    msg: "Java 8 is NOT installed"
  when: (not java8_installed)

- name: Install latest jdk 1.8
  yum:
    name: java-1.8.0-openjdk-headless.x86_64
    state: latest
  become: true
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
        (not java8_installed) and
        (offline is undefined)

- name: Copy java
  copy:
    src: resources/bin/java/
    dest: /tmp/java/
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
         (not java8_installed) and
        (offline is defined)

- name: Get java files
  find:
    paths: /tmp/java
    excludes: readme.txt
  register: java_files
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
         (not java8_installed) and
        (offline is defined)

- name : Init java files list
  set_fact:
     java_list: []
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
        (not java8_installed) and
        (offline is defined)

- name : Build java files list
  set_fact:
     java_list: "{{ java_list + [ item.path ] }}"
  with_items: "{{java_files.files}}"
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
         (not java8_installed) and
        (offline is defined)

- name: Creates java alternative directory
  become: true
  file:
    path: /usr/local/oracle-java-8
    state: directory
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
         (not java8_installed) and
        (offline is defined)

- name: Extract java archive from local source
  become: true
  unarchive:
    src: "{{ JAVA_DIST_URL }}"
    dest: /usr/local/oracle-java-8
    mode: 0755
    remote_src: no
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
         (not java8_installed) and
        (offline is defined)

- name: Get files in /usr/local/oracle-java-8
  find:
    paths: "/usr/local/oracle-java-8"
    file_type: directory
  register: found_files
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
         (not java8_installed) and
        (offline is defined)

- name: Get latest file in /usr/local/oracle-java-8
  set_fact:
    latest_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
         (not java8_installed) and
        (offline is defined)

- name: Change java
  become: true
  alternatives:
    name: java
    link: /usr/bin/java
    path: "{{ latest_file.path }}/jre/bin/java"
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
         (not java8_installed) and
        (offline is defined)

- name: Link keytool
  become: true
  alternatives:
    name: keytool
    link: /usr/bin/keytool
    path: "{{ latest_file.path }}/jre/bin/keytool"
  when: (ansible_distribution == 'CentOS' or
         ansible_distribution == 'Red Hat Enterprise Linux') and
         (not java8_installed) and
        (offline is defined)
