
- name: Start service Yorc
  service:
    name: yorc
    state: started
    enabled: yes
  become: true

- name: Ensure Yorc is running
  command: systemctl status yorc
  ignore_errors: false

- name: Ensure a crontab is initialized
  cron:
    name: "InitCrontab"
    minute: "0"
    hour: "0"
    job: "ls -alh > /dev/null"

- name: Remove init job from crontab
  cron:
    name: "InitCrontab"
    state: absent
