
- name: Start service elasticsearch
  service:
    name: elasticsearch
    state: started
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
