
- name: Create temporary folder
  tempfile:
    state: directory
  register: temp_dir

- name: Upload resource {{ resources_file_path }} on remote in {{ temp_dir.path }}/resources.yaml
  copy:
    src: "{{ resources_file_path }}"
    dest: "{{ temp_dir.path  }}/resources.yaml"
  ignore_errors: yes

- name: "Stat {{ temp_dir.path }}/resources.yaml"
  stat:
    path: "{{ temp_dir.path }}/resources.yaml"
  register: resources_file

- name: Slurp resources files
  slurp:
    src: "{{ temp_dir.path }}/resources.yaml"
  register: resources_slurped
  when: resources_file.stat.exists

- set_fact:
    resources_yaml: "{{resources_slurped['content'] | b64decode | from_yaml}}"
  when: resources_file.stat.exists

- name: Here is the resource content
  debug:
    var: resources_yaml
  when: (resources_yaml is defined)

- name: Finally remove temporary folder
  file:
    path: "{{ temp_dir.path }}"
    state: absent
