---
- name: initialize pvsize
  set_fact:
     pvsize: "{{ k8s.yorc.pvsize | default(k8s_yorc_pvsize) }}"

- name: display action
  debug:
     var: action

- name: perform action on yorc pvc 
  include_role:
    name: k8s/commons/namespaced-resource/{{ action }}
  when: (k8s.yorc.namespace is defined)
  vars:
    namespace: "{{ k8s.yorc.namespace }}"
    file: "{{ k8s.yorc.pvfile }}.pvc"

- name: perform action on yorc pv 
  include_role:
    name: k8s/commons/cluster-resource/{{ action }}
  when: (k8s.yorc.namespace is defined) and 
         (((k8s.yorc.create_pv is defined) and (k8s.yorc.create_pv)) or
          (action == 'delete'))
  vars:
    namespace: "{{ k8s.yorc.namespace }}"
    file: "{{ k8s.yorc.pvfile }}"

