---

- name: display action
  debug:
     var: action
     
- name: initialize pvsize
  set_fact:
     pvsize: "{{ k8s.a4c.pvsize | default(k8s_a4c_pvsize) }}"

- name: initialize pvlogssize
  set_fact:
     pvlogssize: "{{ k8s.a4c.pvlogssize | default(k8s_a4c_pvlogssize) }}"     

- name: initialize image
  set_fact:
     image: "{{ k8s.a4c.image | default(k8s_a4c_image) }}"

- name: init deployment file
  set_fact:
    file: "{{ k8s.a4c.statefulset_file | default ('a4cstatefulset.yml.j2') }}"

- name: perform action on a4c statefulset
  include_role:
    name: k8s/commons/namespaced-resource/{{ action }}
  when: (k8s.a4c.namespace is defined)
  vars:
    namespace: "{{ k8s.a4c.namespace }}"
