
- name: Ensure the 'offline' variable is defined
  set_fact :
    offline: false
  when: offline is not defined

- name: Creates java alternative directory
  become: true
  file:
    path: /usr/local/openjdk
    state: directory

- name: Extract Java archive from remote source
  unarchive:
    src: "{{ JAVA_DIST_URL }}"
    dest: /usr/local/openjdk
    mode: 0755
    remote_src: yes
  become: true
  when: (not offline)

- name: Extract Java archive from local source
  unarchive:
    src: "{{ JAVA_DIST_URL }}"
    dest: /usr/local/openjdk
    mode: 0755
    remote_src: no
  become: true
  when: (offline)

- name: Get files in /usr/local/openjdk
  find:
    paths: "/usr/local/openjdk"
    file_type: directory
  register: found_files

- name: Get latest file in /usr/local/openjdk/{{ java_dir }}
  set_fact:
    latest_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"

- name: Change java
  become: true
  alternatives:
    name: java
    link: /usr/bin/java
    path: "{{ latest_file.path }}/bin/java"

- name: Link keytool
  become: true
  alternatives:
    name: keytool
    link: /usr/bin/keytool
    path: "{{ latest_file.path }}/bin/keytool"
