---

- hosts: jmeter
  name: Uninstall loadtests
  roles:
    - loadtests/delete-loadtests

- hosts: a4cfront
  gather_facts: no
  name: Delete A4C front (Nginx, consul and consul-template).
  roles:
    - a4c_front/delete-a4cfront
    - nginx/delete-nginx
    - consul/delete-consul

- hosts: a4c
  gather_facts: no
  serial: 1
  name: unmount shared volume for A4C.
  roles:
    - commons/define_commons_vars
    - { role: nfs/rm_nfs,
        ha_group: 'a4c'
      }

- hosts: yorc
  gather_facts: no
  serial: 1
  name: unmount shared volume for Yorc.
  roles:
    - commons/define_commons_vars
    - { role: nfs/rm_nfs,
        ha_group: 'yorc'
      }

- hosts: a4c
  gather_facts: no
  name: Delete A4C
  roles:
    - commons/define_commons_vars
    - a4c/delete-a4c
    - consul/delete-consul
    - { role: rsync/delete-sync,
        component_name: 'a4c'
      }

- hosts: yorcfront
  gather_facts: no
  name: Stop Yorc front (Nginx).
  roles:
    - nginx/delete-nginx

- hosts: yorc
  gather_facts: no
  name: Delete Yorc
  become: false
  roles:
    - commons/define_commons_vars
    - yorc/delete-yorc
    - consul/delete-consul

- hosts: consul
  gather_facts: no
  name: Delete Consul
  become: false
  roles:
    - consul/delete-consul

- hosts: localhost
  gather_facts: no
  become: false
  roles:
    - commons/define_commons_vars
    - role: k8s/commons/define_commons_vars
      when: k8s is defined
    - k8s/a4c/delete
    - k8s/yorc/delete
    - k8s/consul/delete

- hosts: elasticsearch
  gather_facts: no
  name: Delete Elasticsearch
  roles:
    - elasticsearch/delete-elasticsearch

- hosts: a4c
  gather_facts: no
  name: unmount shared volume for A4C.
  roles:
    - commons/define_commons_vars
    - { role: nfs/unmount_nfs,
        ha_group: 'a4c'
      }

- hosts: yorc
  gather_facts: no
  name: unmount shared volume for Yorc.
  roles:
    - commons/define_commons_vars
    - { role: nfs/unmount_nfs,
        ha_group: 'yorc'
      }
