---

- hosts: a4cfront
  name: Delete A4C front (Nginx, consul and consul-template).
  roles:
    - a4c_front/delete-a4cfront
    - nginx/delete-nginx
    - consul/delete-consul

- hosts: a4c
  gather_facts: no
  serial: 1
  name: unmount shared volume for A4C.
  roles:
    - { role: commons/rm_nfs,
        ha_group: 'a4c'
      }

- hosts: yorc
  gather_facts: no
  serial: 1
  name: unmount shared volume for Yorc.
  roles:
    - { role: commons/rm_nfs,
        ha_group: 'yorc'
      }

- hosts: a4c
  name: Delete A4C
  roles:
    - a4c/delete-a4c
    - consul/delete-consul
    - rsync/delete-sync

- hosts: yorcfront
  name: Stop Yorc front (Nginx).
  roles:
    - nginx/delete-nginx

- hosts: yorc
  name: Delete Yorc
  become: false
  roles:
    - yorc/delete-yorc
    - consul/delete-consul

- hosts: consul
  name: Delete Consul
  become: false
  roles:
    - consul/delete-consul

- hosts: elasticsearch
  name: Delete Elasticsearch
  roles:
    - elasticsearch/delete-elasticsearch

- hosts: a4c
  gather_facts: no
  name: unmount shared volume for A4C.
  roles:
    - { role: commons/unmount_nfs,
        ha_group: 'a4c'
      }

- hosts: yorc
  gather_facts: no
  name: unmount shared volume for Yorc.
  roles:
    - { role: commons/unmount_nfs,
        ha_group: 'yorc'
      }
  
