---
- hosts: a4cconfig
  name: Fetch keypass certificates / keys
  become: false

  roles:
    - commons/define_commons_vars
    - { role: 'keypass/fetch_keypass_ca_certificate',
        keypass_key: 'Plateforme/Securite/pki/Autorite de Certification Secondaire - Plateforme',
        keypass_custom_property: 'fullchain'
      }
    - { role: 'keypass/fetch_keypass_host_certificate_key',
        keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur Consul',
        machine_name: 'consul',
        keypass_custom_property: 'cert.certificate',
        file_suffix_var_name: 'ssl_host_cert_suffix'
      }
    - { role: 'keypass/fetch_keypass_host_certificate_key',
        keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur Consul',
        machine_name: 'consul',
        keypass_custom_property: 'cert.private.key',
        file_suffix_var_name: 'ssl_host_key_suffix'
      }
    - { role: 'keypass/fetch_keypass_host_certificate_key',
        keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur A4C Technique',
        machine_name: 'a4c.technique.artemis',
        keypass_custom_property: 'cert.certificate',
        file_suffix_var_name: 'ssl_host_cert_suffix'
      }
    - { role: 'keypass/fetch_keypass_host_certificate_key',
        keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur A4C Technique',
        machine_name: 'a4c.technique.artemis',
        keypass_custom_property: 'cert.private.key',
        file_suffix_var_name: 'ssl_host_key_suffix'
      }
    - { role: 'keypass/fetch_keypass_host_certificate_key',
        keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur A4C Admin',
        machine_name: 'a4c.admin.artemis',
        keypass_custom_property: 'cert.certificate',
        file_suffix_var_name: 'ssl_host_cert_suffix'
      }
    - { role: 'keypass/fetch_keypass_host_certificate_key',
        keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur A4C Admin',
        machine_name: 'a4c.admin.artemis',
        keypass_custom_property: 'cert.private.key',
        file_suffix_var_name: 'ssl_host_key_suffix'
      }
    - { role: 'keypass/fetch_keypass_host_certificate_key',
        keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur A4C Technique',
        machine_name: 'a4c',
        keypass_custom_property: 'cert.certificate',
        file_suffix_var_name: 'ssl_host_cert_suffix'
      }
    - { role: 'keypass/fetch_keypass_host_certificate_key',
        keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur A4C Technique',
        machine_name: 'a4c',
        keypass_custom_property: 'cert.private.key',
        file_suffix_var_name: 'ssl_host_key_suffix'
      }
    - { role: 'keypass/fetch_keypass_property_to_file',
        keypass_key: 'Plateforme/Service applicatif/a4c/Compte par default - Admin A4C',
        keypass_property: 'username',
        target_file_path: '{{ data_dir }}/keepass.yml',
        target_field: 'a4c_admin_usr'
      }
    - { role: 'keypass/fetch_keypass_property_to_file',
        keypass_key: 'Plateforme/Service applicatif/a4c/Compte par default - Admin A4C',
        keypass_property: 'password',
        target_file_path: '{{ data_dir }}/keepass.yml',
        target_field: 'a4c_admin_pwd'
      }
    - { role: 'keypass/fetch_keypass_property_pair_to_file',
        keypass_key: "Plateforme/Controle d'acces et Firewall/smd/Compte Technique A4C",
        keypass_property1: 'username',
        keypass_property2: 'password',
        target_file_path: '{{ data_dir }}/keepass.yml',
        plugin_name: 'datagouv_mls',
        target_field: 'applicationPostCredentials'
      }
    - { role: 'keypass/fetch_keypass_property_pair_to_file',
        keypass_key: "Plateforme/Controle d'acces et Firewall/smd/Compte Technique A4C",
        keypass_property1: 'username',
        keypass_property2: 'password',
        target_file_path: '{{ data_dir }}/keepass.yml',
        plugin_name: 'datagouv_mls',
        target_field: 'getPdsCredentials'
      }
    - { role: 'keypass/fetch_keypass_property_pair_to_file',
        keypass_key: "Plateforme/Gestion de la donnee/atlas/Compte Technique a4c",
        keypass_property1: 'username',
        keypass_property2: 'password',
        target_file_path: '{{ data_dir }}/keepass.yml',
        plugin_name: 'datagouv_mls',
        target_field: 'applicationDeleteCredentials'
      }
