---

- hosts: a4cconfig
  name: Import services from dump
  become: false
  roles:
    - commons/define_commons_vars
    - a4c/config/define_a4c_url
    - { role: 'a4c/config/create_services',
        resources_file_artifact: 'resources/importsvc.yml'
      }
