---
- hosts: elasticsearch
  name: Install all common dependencies.
  roles:
    - commons/install-common-dependencies
    - commons/add_dns_server

- hosts: elasticsearch
  name: Install configure and start Elasticsearch.
  roles:
    - elasticsearch/stop-elasticsearch
    - install-java
    - elasticsearch/install-elasticsearch
    - elasticsearch/configure-elasticsearch
    - elasticsearch/start-elasticsearch
