---
- hosts:
    - yorc
    - yorcfront
  name: Install all common dependencies.
  gather_facts: no
  roles:
    - commons/install-common-dependencies
    - commons/add_dns_server
    # - commons/remove_epel_repo

- hosts: yorc
  name: Install configure and start Yorc.
  roles:
    - commons/define_commons_vars
    - yorc/stop-yorc
    - consul/stop-consul
    - yorc/install-dependencies
    - consul/install-consul
    - { role: consul/configure-consul, consul_mode: 'client' }
    - install-java
    - yorc/install-yorc
    - yorc/configure-yorc
    - spark/install-spark
    - { role: spark/define-spark-home, spark_user_var: 'yorc_user' }    
    - consul/start-consul
    - yorc/start-yorc

- hosts: yorcfront
  name: Install Yorc front (Nginx).
  roles:
    - commons/define_commons_vars
    - nginx/stop-nginx
    - nginx/install-nginx
    - yorc/configure-nginx
    - nginx/start-nginx
