---
- hosts:
    - a4c
    - a4cfront
  name: Install all common dependencies
  roles:
    - commons/install-common-dependencies
    - commons/add_dns_server
    # - commons/remove_epel_repo

- hosts: a4c
  name: Eventually migrate a4c working directory
  gather_facts: no
  # we want this operation to be executed sequencially
  serial: 1
  roles:
    - a4c/migrate-a4c-working-dir

- hosts: a4c
  name: Install and configure A4C
  roles:
    - commons/define_commons_vars
    - consul/stop-consul
    - a4c/stop-a4c
    - install-java
    - a4c/install-a4c
    - consul/install-consul
    - { role: consul/configure-consul, consul_mode: 'client' }
    - a4c/configure-a4c
    - consul/start-consul

- hosts: a4cfront
  name: Install A4C front (Nginx, consul and consul-template)
  roles:
    - commons/define_commons_vars
    - nginx/stop-nginx
    - a4c_front/stop-consul-template
    - consul/stop-consul
    - nginx/install-nginx
    - consul/install-consul
    - { role: consul/configure-consul, consul_mode: 'client' }
    - a4c_front/configure-nginx
    - a4c_front/install-consul-template
    - a4c_front/configure-consul-template
    - consul/start-consul
    - nginx/start-nginx
    - a4c_front/start-consul-template

- hosts: a4c
  name: Start A4C
  gather_facts: no
  # we want each A4C to be started sequencially in case of HA
  serial: 1
  roles:
    - { role: a4c/config/define_a4c_url, should_login: false }
    - a4c/start-a4c
    - a4c/config/wait_a4c_fullstart
