---
- hosts: consului
  name: Install all common dependencies.
  gather_facts: no
  roles:
    - commons/install-common-dependencies
    - commons/add_dns_server
    # - commons/remove_epel_repo

- hosts: consului
  name: Install configure and start consul.
  roles:
    - commons/debug_vars
    - commons/define_commons_vars
    - consul/stop-consul
    - consul/install-consul
    - consul/configure-consul-gossip-keygen
    - { role: consul/configure-consul, consul_mode: 'client', force_no_tls: true, force_consul_http_port: 80 }
    - consul/start-consul
    - commons/debug_vars
