---

- hosts: consul
  name: Try writing/reading into/from inventory.
  roles:
    - sandbox/write_inventory
    - { role: 'sandbox/read_inventory',
        inventory_resource_path: group_vars/all/hello.yml
      }

- hosts: a4cfront
  name: Try reading from inventory.
  roles:
    - { role: 'sandbox/read_inventory',
        inventory_resource_path: group_vars/all/hello.yml
      }

- hosts: a4cfront
  name: Try reading from inventory (writted locally manually).
  roles:
    - { role: 'sandbox/read_inventory',
        inventory_resource_path: group_vars/localinvotory.yml
      }
