---

- hosts: a4cfront
  name: Try reading extras resource var.
  roles:
    - sandbox/read_extras_var
    - { role: 'sandbox/slurp_extras_resource',
        resources_file_path: 'resources/sandbox.yml'
      }
    - { role: 'sandbox/slurp_extras_resource',
        resources_file_path: 'sandbox.yml'
      }
    - { role: 'sandbox/slurp_extras_resource_remote',
        resources_file_path: 'resources/sandbox.yml'
      }
