---

- hosts: consul
  name: Try writing/reading into/from inventory.
  roles:
    - sandbox/write_inventory
    - sandbox/read_inventory

- hosts: a4cfront
  name: Try reading from inventory.
  roles:
    - sandbox/read_inventory
