---
# - hosts: a4c
#   gather_facts: no
#   serial: 1  
#   name: Install NFS and mount shared volume for A4C.
#   roles:
#     - { role: commons/prepare_nfs,
#         ha_group: 'a4c',
#         create_home: 'yes'
#       }

- hosts: yorc
  gather_facts: no
  serial: 1
  name: Install NFS and mount shared volume for Yorc.
  roles:
    - { role: commons/prepare_nfs,
        ha_group: 'yorc',
        create_home: 'yes'
      }
