---

- hosts: a4cconfig
  name: Sandbox, play with plays !
  become: false
  roles:
    - commons/define_commons_vars
    - a4c/config/define_a4c_url
    - { role: 'a4c/config/get_orchectrator',
        orchestratorName: 'Yorc'
      }
    - { role: 'a4c/config/get_location',
        location_name: 'Default'
      }    
    - { role: 'a4c/config/create_services',
        resources_file_artifact: 'resources/services.yaml'
      }

    # - { role: 'keypass/fetch_keypass_ca_certificate',
    #     keypass_key: 'Plateforme/Securite/pki/Autorite de Certification Principale',
    #     keypass_custom_property: 'ca'
    #   }
    # - { role: 'keypass/fetch_keypass_host_certificate_key',
    #     keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur - front',
    #     machine_name: 'sva-a4c-front-1',
    #     keypass_custom_property: 'cert.certificate',
    #     file_suffix_var_name: 'ssl_host_cert_suffix'
    #   }
    # - { role: 'keypass/fetch_keypass_host_certificate_key',
    #     keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur - front',
    #     machine_name: 'sva-a4c-front-1',
    #     keypass_custom_property: 'cert.private.key',
    #     file_suffix_var_name: 'ssl_host_key_suffix'
    #   }
    # - { role: 'keypass/fetch_keypass_host_certificate_key',
    #     keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur - a4c - vm1',
    #     machine_name: 'sva-a4c-a4c-1',
    #     keypass_custom_property: 'cert.certificate',
    #     file_suffix_var_name: 'ssl_host_cert_suffix'
    #   }
    # - { role: 'keypass/fetch_keypass_host_certificate_key',
    #     keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur - a4c - vm1',
    #     machine_name: 'sva-a4c-a4c-1',
    #     keypass_custom_property: 'cert.private.key',
    #     file_suffix_var_name: 'ssl_host_key_suffix'
    #   }
    # - { role: 'keypass/fetch_keypass_host_certificate_key',
    #     keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur - a4c - vm2',
    #     machine_name: 'sva-a4c-a4c-2',
    #     keypass_custom_property: 'cert.certificate',
    #     file_suffix_var_name: 'ssl_host_cert_suffix'
    #   }
    # - { role: 'keypass/fetch_keypass_host_certificate_key',
    #     keypass_key: 'Plateforme/Service applicatif/a4c/Certificat Serveur - a4c - vm2',
    #     machine_name: 'sva-a4c-a4c-2',
    #     keypass_custom_property: 'cert.private.key',
    #     file_suffix_var_name: 'ssl_host_key_suffix'
    #   }
    # - commons/define_commons_vars
    # - a4c/config/define_a4c_url
    #   # Orchestrator & Location
    # - { role: 'a4c/config/get_orchectrator',
    #     orchestratorName: 'Yorc'
    #   }
    # - { role: 'a4c/config/get_location',
    #     location_name: 'Default',
    #     location_type: 'HostsPool'
    #   }
    # - a4c/config/disable_plugins
    # - { role: 'a4c/config/create_location_modifiers',
    #     orchestratorName: 'Yorc',
    #     location_name: 'Default'
    #   }
    # - a4c/config/order_location_modifiers_it
    # - { role: 'a4c/config/create_location_resources',
    #     resources_file_artifact: 'resources/location_resources.yaml'
    #   }
      # Location modifiers
    # - { role: 'a4c/config/setup_location_modifier',
    #     pluginId: 'alien4cloud-yorc-provider',
    #     beanName: 'gangja-resolver-modifier',
    #     phase: 'post-node-match',
    #     modifier_position: 1
    #   }
    # - { role: 'a4c/config/setup_location_modifier',
    #     pluginId: 'alien4cloud-datagouv_mls-plugin',
    #     beanName: 'datagouv_mls-modifier',
    #     phase: 'post-matched-node-setup',
    #     modifier_position: 2
    #   }
    # - { role: 'a4c/config/setup_location_modifier',
    #     pluginId: 'alien4cloud-kubernetes-plugin',
    #     beanName: 'kubernetes-adapter-modifier',
    #     phase: 'post-matched-node-setup',
    #     modifier_position: 3
    #   }
    # - { role: 'a4c/config/setup_location_modifier',
    #     pluginId: 'alien4cloud-consul-publisher-plugin',
    #     beanName: 'consul-publisher',
    #     phase: 'post-matched-node-setup',
    #     modifier_position: 4
    #   }
    # - { role: 'a4c/config/setup_location_modifier',
    #     pluginId: 'alien4cloud-ssi-network_policy-plugin',
    #     beanName: 'ssi-network_policy-modifier',
    #     phase: 'post-matched-node-setup',
    #     modifier_position: 5
    #   }
    # - { role: 'a4c/config/setup_location_modifier',
    #     pluginId: 'alien4cloud-k8s-spark-jobs',
    #     beanName: 'k8s-spark-jobs-modifier',
    #     phase: 'post-matched-node-setup',
    #     modifier_position: 6
    #   }
    # - { role: 'a4c/config/setup_location_modifier',
    #     pluginId: 'alien4cloud-supervision',
    #     beanName: 'kubernetes-supervision-modifier',
    #     phase: 'post-matched-node-setup',
    #     modifier_position: 7
    #   }
    #   # Eventually disable some plugins
    # - a4c/config/disable_plugins
    # - { role: 'a4c/config/create_metaproperties',
    #     resources_file_artifact: 'resources/metaproperties.yaml'
    #   }
    # - a4c/config/git_var
    # - a4c/config/download_upload_csars
    # - a4c/config/upload_csars
    # - { role: 'commons/parse_kubeconfig',
    #     resources_file_artifact: 'resources/kubeconfig'
    #   }
    # - { role: 'a4c/config/create_services',
    #     resources_file_artifact: 'resources/services.yaml'
    #   }
