---

- hosts: a4cfront
  name: Try wrinting into inventory.
  roles:
    - sandbox/write_inventory
    - sandbox/read_inventory

- hosts: yorc
  name: Try reading from inventory.
  roles:
    - sandbox/read_inventory
