
- hosts: elasticsearch
  name: Install configure and start Elasticsearch.
  roles:
    - elasticsearch/start-elasticsearch

- hosts: consul
  name: Install configure and start consul.
  roles:
    - consul/start-consul

- hosts: yorc
  name: Install configure and start Yorc.
  roles:
    - consul/start-consul
    - yorc/start-yorc

- hosts: yorcfront
  name: Install Yorc front (Nginx).
  roles:
    - nginx/start-nginx

- hosts: a4c
  name: Install and configure A4C
  roles:
    - commons/define_commons_vars
    - consul/stop-consul
    - a4c/stop-a4c
    - install-java
    - a4c/install-a4c
    - consul/install-consul
    - { role: consul/configure-consul, consul_mode: 'client' }
    - a4c/configure-a4c
    - consul/start-consul

- hosts: a4cfront
  name: Install A4C front (Nginx, consul and consul-template)
  roles:
    - commons/define_commons_vars
    - consul/start-consul
    - nginx/start-nginx
    - a4c_front/start-consul-template

- hosts: a4c
  name: Start A4C
  gather_facts: no
  # we want each A4C to be started sequencially in case of HA
  serial: 1
  roles:
    - commons/define_commons_vars
    - consul/start-consul
    - a4c/start-a4c
    - { role: a4c/config/define_a4c_url, should_login: false }
    - a4c/config/wait_a4c_fullstart
