---

- hosts: jmeter
  name: Stop loadtests
  roles:
    - loadtests/stop-loadtests

- hosts: a4cfront
  name: Stop A4C front (Nginx, consul and consul-template).
  gather_facts: no
  roles:
    - nginx/stop-nginx
    - a4c_front/stop-consul-template
    - consul/stop-consul

- hosts: yorcfront
  name: Stop Yorc front (Nginx).
  gather_facts: no
  roles:
    - nginx/stop-nginx

- hosts: a4c
  name: Stop Consul & A4C.
  gather_facts: no
  roles:
    - commons/define_commons_vars
    - consul/stop-consul
    - a4c/stop-a4c
    - { role: rsync/stop-sync,
        component_name: 'a4c'
      }
    - { role: rsync/stop-consul-template,
        component_name: 'a4c'
      }

- hosts: yorc
  name: Stop Yorc.
  gather_facts: no
  roles:
    - yorc/stop-yorc
    - consul/stop-consul

- hosts: consul
  name: Stop consul.
  gather_facts: no
  roles:
    - consul/stop-consul

- hosts: localhost
  name: stop k8s pods
  roles:
    - commons/define_commons_vars
    - role: k8s/commons/define_commons_vars
      when: k8s is defined
    - k8s/a4c/stop
    - k8s/yorc/stop
    - k8s/consul/stop

- hosts: elasticsearch
  name: Stop Elasticsearch.
  gather_facts: no
  roles:
    - elasticsearch/stop-elasticsearch
