---

- hosts: a4cfront
  name: Stop A4C front (Nginx, consul and consul-template).
  gather_facts: no
  roles:
    - nginx/stop-nginx
    - a4c_front/stop-consul-template
    - consul/stop-consul

- hosts: yorcfront
  name: Stop Yorc front (Nginx).
  gather_facts: no
  roles:
    - nginx/stop-nginx

- hosts: a4c
  name: Stop Consul & A4C.
  gather_facts: no
  roles:
    - consul/stop-consul
    - a4c/stop-a4c
    - rsync/stop-sync
    - rsync/stop-consul-template

- hosts: yorc
  name: Stop Yorc.
  gather_facts: no
  roles:
    - yorc/stop-yorc
    - consul/stop-consul

- hosts: consul
  name: Stop consul.
  gather_facts: no
  roles:
    - consul/stop-consul

- hosts: elasticsearch
  name: Stop Elasticsearch.
  gather_facts: no
  roles:
    - elasticsearch/stop-elasticsearch
