---
- hosts: a4cconfig
  name: Test the setup deploying an application based on mocks.
  gather_facts: no
  become: false

  roles:
    - commons/define_commons_vars    
    - a4c/config/define_a4c_url
    - { role: 'a4c/config/get_orchectrator',
        orchestratorName: 'Yorc'
      }
    - { role: 'a4c/config/create_location',
        location_name: 'Default',
        location_type: 'OpenStack'
      }
    - { role: 'a4c/config/remove_location_modifier',
        pluginId: 'alien4cloud-datagouv_mls-plugin',
        beanName: 'datagouv_mls-modifier',
        phase: 'post-matched-node-setup'
      }
    - { role: 'a4c/config/disable_plugin',
        pluginId: 'alien4cloud-datagouv_mls-plugin'
      }
    - { role: 'a4c/config/test_application_deployment',
        topologyTemplateVersionId: '1TinyMock:2.1.0-SNAPSHOT',
        applicationName: 'SetupTestApp'
      }
    - { role: 'a4c/config/enable_plugin',
        pluginId: 'alien4cloud-datagouv_mls-plugin'
      }
    - { role: 'a4c/config/setup_location_modifier',
        pluginId: 'alien4cloud-datagouv_mls-plugin',
        beanName: 'datagouv_mls-modifier',
        phase: 'post-matched-node-setup',
        modifier_position: 1
      }
