---
- hosts: a4cconfig
  name: Test the setup deploying an application based on mocks.
  become: false

  roles:
    - a4c/config/define_a4c_url
    - { role: 'roles/a4c/config/test_application_deployment',
        topologyTemplateVersionId: '3MockWithRel:2.1.0-SNAPSHOT',
        applicationName: 'SetupTestApp'
      }
