---
- hosts: a4c
  gather_facts: no
  name: unmount shared volume for A4C.
  roles:
    - { role: commons/unmount_nfs,
        ha_group: 'a4c'
      }

- hosts: yorc
  gather_facts: no
  name: unmount shared volume for Yorc.
  roles:
    - { role: commons/unmount_nfs,
        ha_group: 'yorc'
      }
