---
- hosts: a4c
  name: Stop A4C
  roles:
    - commons/define_commons_vars
    - a4c/stop-a4c

- hosts: yorc
  name: Stop Yorc
  roles:
    - commons/define_commons_vars
    - yorc/stop-yorc

- hosts: elasticsearch
  name: Remove previous Elasticsearch, Install configure and start new Elasticsearch.
  roles:
    - commons/define_commons_vars
    - elasticsearch/uninstall-elasticsearch
    - elasticsearch/install-elasticsearch
    - elasticsearch/configure-elasticsearch
    - elasticsearch/start-elasticsearch

- hosts: yorc
  name: start Yorc.
  roles:
    - commons/define_commons_vars
    - yorc/start-yorc

- hosts: a4c
  name: Start A4C
  gather_facts: no
  # we want each A4C to be started sequencially in case of HA
  serial: 1
  roles:
    - { role: a4c/config/define_a4c_url, should_login: false }
    - a4c/start-a4c
    - a4c/config/wait_a4c_fullstart
