---
- name: Delete resource
  k8s:
    state: absent
    kubeconfig: "{{ kubeConfig}}"           
    definition: "{{ lookup('template', file) }}"
    wait: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
