---

- name: Copy CSAR archives
  copy:
    src: resources/csars/
    dest: /tmp/csars/

- name: Get CSAR archives
  find:
    paths: /tmp/csars/
    patterns: "*.zip"
  register: cars_files

- set_fact:
    alien_url: "{{ a4c_protocol }}://{{ a4c_ip }}:{{ a4c_port }}"

- name: Login onto A4C
  uri:
    url: "{{ alien_url }}/login?username={{ a4c_admin_usr }}&password={{ a4c_admin_pwd }}&submit=Login"
    method: POST
    return_content: yes
    status_code: 302
    validate_certs: no
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: login

- set_fact:
    session_id: "{{ login.set_cookie.split(';')[0] }}"

- name: Upload CSAR archive to A4C
  shell: "curl -k -X POST -H 'cookie: {{ session_id }}' -F file=@{{ item.path }} '{{ alien_url }}/rest/latest/csars'"
  with_items: "{{ cars_files.files | sort(attribute='path') | list }}"
