---

- name: Copy CSAR archives
  copy:
    src: resources/csars/
    dest: /tmp/csars/

- name: Get CSAR archives
  find:
    paths: /tmp/csars/
    patterns: "*.zip"
  register: cars_files

- name: Upload CSAR archive to A4C
  shell: "curl -k -X POST -H 'cookie: {{ session_id }}' -F file=@{{ item.path }} '{{ alien_url }}/rest/latest/csars'"
  with_items: "{{ cars_files.files | sort(attribute='path') | list }}"
