---

- name: Initialize a variable indicating if the plugin was found
  set_fact:
    plugin_found: false

- name: Search for plugin
  uri:
    url: "{{ alien_url }}/rest/latest/plugins?from=0&query={{ pluginId }}&size=1"
    method: GET
    return_content: yes
    validate_certs: no
    headers:
      Cookie: "{{ session_id }}"
    body_format: json
    status_code: 200
  register: plugin_list_result

- name: Parse the plugin list as JSON
  set_fact:
    plugin_list: "{{ plugin_list_result.content | from_json }}"

- name: Here is the plugins list
  debug:
    var: plugin_list

- name: Define a variable indicating if the plugin was found
  set_fact:
    plugin_found: "{{ plugin_list.data.totalResults > 0 }}"

- name: Is the plugin found ?
  debug:
    var: plugin_found

- name: Define a variable indicating if the plugin is enabled
  set_fact:
    plugin_enabled: "{{ plugin_list.data.data[0].enabled == true }}"
  when: (plugin_found)

- name: Is the plugin enabled ?
  debug:
    var: plugin_enabled
  when: (plugin_found)

- name: Get modifiers for orchestrator/location
  uri:
    url: "{{ alien_url }}/rest/latest/orchestrators/{{ orchestratorId }}/locations/{{ locationId }}/modifiers"
    method: GET
    return_content: yes
    validate_certs: no
    headers:
      Cookie: "{{ session_id }}"
    body_format: json
    status_code: 200
  register: result
  when: (plugin_found and plugin_enabled)

- name: Parse the modifier list as JSON
  set_fact:
    location_modifiers: "{{ result.content | from_json }}"
  when: (plugin_found and plugin_enabled)

# - name: Just to add array index as a property (using namespace)
#   set_fact:
#     location_modifiers: |
#       {% set result = [] -%}
#       {% set count = namespace(value=0) -%}
#       {% for modifier in location_modifiers.data -%}
#         {% set ignored = result.extend([{'pluginId': modifier['pluginId'], 'beanName': modifier['beanName'], 'phase': modifier['phase'], 'index': count.value}]) -%}
#         {% set count.value = count.value + 1 -%}
#       {%- endfor %}
#       {{ result }}

- name: Just to add array index as a property
  set_fact:
    location_modifiers: |
      {% set result = [] -%}
      {% for modifier in location_modifiers.data -%}
        {% set ignored = result.extend([{'pluginId': modifier['pluginId'], 'beanName': modifier['beanName'], 'phase': modifier['phase'], 'index': loop.index0 }]) -%}
      {%- endfor %}
      {{ result }}
  when: (plugin_found and plugin_enabled)

- debug:
    var: location_modifiers
  when: (plugin_found and plugin_enabled)

- name: Build the JSON query for searching location modifier for this plugin
  set_fact:
    query: "[? pluginId=='{{ pluginId }}' && beanName=='{{ beanName }}' && phase=='{{ phase }}']"
  when: (plugin_found and plugin_enabled)

# This is important since this role can be played several times in the same play
# that's also why we test (plugin_modifier is defined) and (plugin_modifier.pluginId is defined) below
- name: override plugin_modifier to null
  set_fact:
    plugin_modifier:
  when: (plugin_found and plugin_enabled)

- name: Search for modifier
  set_fact:
    plugin_modifiers: "{{ location_modifiers | json_query(query) }}"
  when: (plugin_found and plugin_enabled)

- name: Here is the plugin_modifiers length
  debug:
    msg: "{{ plugin_modifiers | length }}"
  when: (plugin_found and plugin_enabled)

- name: Get the first in the list
  set_fact:
    plugin_modifier: "{{ plugin_modifiers | first }}"
  when: (plugin_found and plugin_enabled) and (plugin_modifiers | length > 0)

- name: Here is the modifier
  debug:
    var: plugin_modifier
  when: (plugin_found and plugin_enabled) and (plugin_modifier is defined) and (plugin_modifier.pluginId is defined)

- name: Create location modifier since it can not be found
  uri:
    url: "{{ alien_url }}/rest/latest/orchestrators/{{ orchestratorId }}/locations/{{ locationId }}/modifiers"
    method: POST
    return_content: yes
    validate_certs: no
    headers:
      Cookie: "{{ session_id }}"
    body:
      pluginId: "{{ pluginId }}"
      beanName: "{{ beanName }}"
      phase: "{{ phase }}"
    body_format: json
    status_code: 200
  when: (plugin_found and plugin_enabled) and ((plugin_modifier is not defined) or (plugin_modifier.pluginId is not defined))

- name: Get modifiers for orchestrator/location
  uri:
    url: "{{ alien_url }}/rest/latest/orchestrators/{{ orchestratorId }}/locations/{{ locationId }}/modifiers"
    method: GET
    return_content: yes
    validate_certs: no
    headers:
      Cookie: "{{ session_id }}"
    body_format: json
    status_code: 200
  register: result
  when: (plugin_found and plugin_enabled) and ((plugin_modifier is not defined) or (plugin_modifier.pluginId is not defined))

- name: Parse modifier list as JSON
  set_fact:
    location_modifiers: "{{ result.content | from_json }}"
  when: (plugin_found and plugin_enabled) and ((plugin_modifier is not defined) or (plugin_modifier.pluginId is not defined))

- name: Just to add array index as a property
  set_fact:
    location_modifiers: |
      {% set result = [] -%}
      {% for modifier in location_modifiers.data -%}
        {% set ignored = result.extend([{'pluginId': modifier['pluginId'], 'beanName': modifier['beanName'], 'phase': modifier['phase'], 'index': loop.index0 }]) -%}
      {%- endfor %}
      {{ result }}
  when: (plugin_found and plugin_enabled) and ((plugin_modifier is not defined) or (plugin_modifier.pluginId is not defined))

- name: Search modifier using JSON query
  set_fact:
    plugin_modifier: "{{ location_modifiers | json_query(query) | first }}"
  when: (plugin_found and plugin_enabled) and ((plugin_modifier is not defined) or (plugin_modifier.pluginId is not defined))

- name: Change location modifiers orders
  uri:
    url: "{{ alien_url }}/rest/latest/orchestrators/{{ orchestratorId }}/locations/{{ locationId }}/modifiers/from/{{ plugin_modifier.index }}/to/{{ modifier_position }}"
    method: PUT
    return_content: yes
    validate_certs: no
    headers:
      Cookie: "{{ session_id }}"
    status_code: 200
  when: (plugin_found and plugin_enabled) and (plugin_modifier.index != modifier_position)
